// Code generated by ent, DO NOT EDIT.

package apiquotatracker

import (
	"sheng-go-backend/ent/predicate"
	"sheng-go-backend/ent/schema/ulid"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id ulid.ID) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id ulid.ID) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id ulid.ID) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...ulid.ID) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...ulid.ID) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id ulid.ID) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id ulid.ID) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id ulid.ID) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id ulid.ID) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldUpdatedAt, v))
}

// Month applies equality check predicate on the "month" field. It's identical to MonthEQ.
func Month(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldMonth, v))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldYear, v))
}

// CallCount applies equality check predicate on the "call_count" field. It's identical to CallCountEQ.
func CallCount(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldCallCount, v))
}

// QuotaLimit applies equality check predicate on the "quota_limit" field. It's identical to QuotaLimitEQ.
func QuotaLimit(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldQuotaLimit, v))
}

// QuotaExceeded applies equality check predicate on the "quota_exceeded" field. It's identical to QuotaExceededEQ.
func QuotaExceeded(v bool) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldQuotaExceeded, v))
}

// OverrideEnabled applies equality check predicate on the "override_enabled" field. It's identical to OverrideEnabledEQ.
func OverrideEnabled(v bool) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldOverrideEnabled, v))
}

// NotificationSent applies equality check predicate on the "notification_sent" field. It's identical to NotificationSentEQ.
func NotificationSent(v bool) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldNotificationSent, v))
}

// LastCallAt applies equality check predicate on the "last_call_at" field. It's identical to LastCallAtEQ.
func LastCallAt(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldLastCallAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLTE(FieldUpdatedAt, v))
}

// MonthEQ applies the EQ predicate on the "month" field.
func MonthEQ(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldMonth, v))
}

// MonthNEQ applies the NEQ predicate on the "month" field.
func MonthNEQ(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldMonth, v))
}

// MonthIn applies the In predicate on the "month" field.
func MonthIn(vs ...int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldIn(FieldMonth, vs...))
}

// MonthNotIn applies the NotIn predicate on the "month" field.
func MonthNotIn(vs ...int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNotIn(FieldMonth, vs...))
}

// MonthGT applies the GT predicate on the "month" field.
func MonthGT(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGT(FieldMonth, v))
}

// MonthGTE applies the GTE predicate on the "month" field.
func MonthGTE(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGTE(FieldMonth, v))
}

// MonthLT applies the LT predicate on the "month" field.
func MonthLT(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLT(FieldMonth, v))
}

// MonthLTE applies the LTE predicate on the "month" field.
func MonthLTE(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLTE(FieldMonth, v))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLTE(FieldYear, v))
}

// CallCountEQ applies the EQ predicate on the "call_count" field.
func CallCountEQ(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldCallCount, v))
}

// CallCountNEQ applies the NEQ predicate on the "call_count" field.
func CallCountNEQ(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldCallCount, v))
}

// CallCountIn applies the In predicate on the "call_count" field.
func CallCountIn(vs ...int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldIn(FieldCallCount, vs...))
}

// CallCountNotIn applies the NotIn predicate on the "call_count" field.
func CallCountNotIn(vs ...int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNotIn(FieldCallCount, vs...))
}

// CallCountGT applies the GT predicate on the "call_count" field.
func CallCountGT(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGT(FieldCallCount, v))
}

// CallCountGTE applies the GTE predicate on the "call_count" field.
func CallCountGTE(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGTE(FieldCallCount, v))
}

// CallCountLT applies the LT predicate on the "call_count" field.
func CallCountLT(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLT(FieldCallCount, v))
}

// CallCountLTE applies the LTE predicate on the "call_count" field.
func CallCountLTE(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLTE(FieldCallCount, v))
}

// QuotaLimitEQ applies the EQ predicate on the "quota_limit" field.
func QuotaLimitEQ(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldQuotaLimit, v))
}

// QuotaLimitNEQ applies the NEQ predicate on the "quota_limit" field.
func QuotaLimitNEQ(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldQuotaLimit, v))
}

// QuotaLimitIn applies the In predicate on the "quota_limit" field.
func QuotaLimitIn(vs ...int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldIn(FieldQuotaLimit, vs...))
}

// QuotaLimitNotIn applies the NotIn predicate on the "quota_limit" field.
func QuotaLimitNotIn(vs ...int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNotIn(FieldQuotaLimit, vs...))
}

// QuotaLimitGT applies the GT predicate on the "quota_limit" field.
func QuotaLimitGT(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGT(FieldQuotaLimit, v))
}

// QuotaLimitGTE applies the GTE predicate on the "quota_limit" field.
func QuotaLimitGTE(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGTE(FieldQuotaLimit, v))
}

// QuotaLimitLT applies the LT predicate on the "quota_limit" field.
func QuotaLimitLT(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLT(FieldQuotaLimit, v))
}

// QuotaLimitLTE applies the LTE predicate on the "quota_limit" field.
func QuotaLimitLTE(v int) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLTE(FieldQuotaLimit, v))
}

// QuotaExceededEQ applies the EQ predicate on the "quota_exceeded" field.
func QuotaExceededEQ(v bool) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldQuotaExceeded, v))
}

// QuotaExceededNEQ applies the NEQ predicate on the "quota_exceeded" field.
func QuotaExceededNEQ(v bool) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldQuotaExceeded, v))
}

// OverrideEnabledEQ applies the EQ predicate on the "override_enabled" field.
func OverrideEnabledEQ(v bool) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldOverrideEnabled, v))
}

// OverrideEnabledNEQ applies the NEQ predicate on the "override_enabled" field.
func OverrideEnabledNEQ(v bool) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldOverrideEnabled, v))
}

// NotificationSentEQ applies the EQ predicate on the "notification_sent" field.
func NotificationSentEQ(v bool) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldNotificationSent, v))
}

// NotificationSentNEQ applies the NEQ predicate on the "notification_sent" field.
func NotificationSentNEQ(v bool) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldNotificationSent, v))
}

// LastCallAtEQ applies the EQ predicate on the "last_call_at" field.
func LastCallAtEQ(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldEQ(FieldLastCallAt, v))
}

// LastCallAtNEQ applies the NEQ predicate on the "last_call_at" field.
func LastCallAtNEQ(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNEQ(FieldLastCallAt, v))
}

// LastCallAtIn applies the In predicate on the "last_call_at" field.
func LastCallAtIn(vs ...time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldIn(FieldLastCallAt, vs...))
}

// LastCallAtNotIn applies the NotIn predicate on the "last_call_at" field.
func LastCallAtNotIn(vs ...time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNotIn(FieldLastCallAt, vs...))
}

// LastCallAtGT applies the GT predicate on the "last_call_at" field.
func LastCallAtGT(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGT(FieldLastCallAt, v))
}

// LastCallAtGTE applies the GTE predicate on the "last_call_at" field.
func LastCallAtGTE(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldGTE(FieldLastCallAt, v))
}

// LastCallAtLT applies the LT predicate on the "last_call_at" field.
func LastCallAtLT(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLT(FieldLastCallAt, v))
}

// LastCallAtLTE applies the LTE predicate on the "last_call_at" field.
func LastCallAtLTE(v time.Time) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldLTE(FieldLastCallAt, v))
}

// LastCallAtIsNil applies the IsNil predicate on the "last_call_at" field.
func LastCallAtIsNil() predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldIsNull(FieldLastCallAt))
}

// LastCallAtNotNil applies the NotNil predicate on the "last_call_at" field.
func LastCallAtNotNil() predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.FieldNotNull(FieldLastCallAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIQuotaTracker) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIQuotaTracker) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIQuotaTracker) predicate.APIQuotaTracker {
	return predicate.APIQuotaTracker(sql.NotPredicates(p))
}
