// Code generated by ent, DO NOT EDIT.

package profilepost

import (
	"fmt"
	"io"
	"sheng-go-backend/ent/schema/ulid"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the profilepost type in the database.
	Label = "profile_post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProfileUsername holds the string denoting the profile_username field in the database.
	FieldProfileUsername = "profile_username"
	// FieldFetchStatus holds the string denoting the fetch_status field in the database.
	FieldFetchStatus = "fetch_status"
	// FieldS3Key holds the string denoting the s3_key field in the database.
	FieldS3Key = "s3_key"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeItems holds the string denoting the items edge name in mutations.
	EdgeItems = "items"
	// Table holds the table name of the profilepost in the database.
	Table = "profile_posts"
	// ItemsTable is the table that holds the items relation/edge.
	ItemsTable = "profile_post_items"
	// ItemsInverseTable is the table name for the ProfilePostItem entity.
	// It exists in this package in order to avoid circular dependency with the "profilepostitem" package.
	ItemsInverseTable = "profile_post_items"
	// ItemsColumn is the table column denoting the items relation/edge.
	ItemsColumn = "profile_post_items"
)

// Columns holds all SQL columns for profilepost fields.
var Columns = []string{
	FieldID,
	FieldProfileUsername,
	FieldFetchStatus,
	FieldS3Key,
	FieldErrorMessage,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProfileUsernameValidator is a validator for the "profile_username" field. It is called by the builders before save.
	ProfileUsernameValidator func(string) error
	// S3KeyValidator is a validator for the "s3_key" field. It is called by the builders before save.
	S3KeyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ulid.ID
)

// FetchStatus defines the type for the "fetch_status" enum field.
type FetchStatus string

// FetchStatusPending is the default value of the FetchStatus enum.
const DefaultFetchStatus = FetchStatusPending

// FetchStatus values.
const (
	FetchStatusPending   FetchStatus = "PENDING"
	FetchStatusCOMPLETED FetchStatus = "COMPLETED"
	FetchStatusFAILED    FetchStatus = "FAILED"
	FetchStatusNotFound  FetchStatus = "NOT_FOUND"
)

func (fs FetchStatus) String() string {
	return string(fs)
}

// FetchStatusValidator is a validator for the "fetch_status" field enum values. It is called by the builders before save.
func FetchStatusValidator(fs FetchStatus) error {
	switch fs {
	case FetchStatusPending, FetchStatusCOMPLETED, FetchStatusFAILED, FetchStatusNotFound:
		return nil
	default:
		return fmt.Errorf("profilepost: invalid enum value for fetch_status field: %q", fs)
	}
}

// OrderOption defines the ordering options for the ProfilePost queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProfileUsername orders the results by the profile_username field.
func ByProfileUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileUsername, opts...).ToFunc()
}

// ByFetchStatus orders the results by the fetch_status field.
func ByFetchStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFetchStatus, opts...).ToFunc()
}

// ByS3Key orders the results by the s3_key field.
func ByS3Key(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3Key, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByItemsCount orders the results by items count.
func ByItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newItemsStep(), opts...)
	}
}

// ByItems orders the results by items terms.
func ByItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e FetchStatus) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *FetchStatus) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = FetchStatus(str)
	if err := FetchStatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid FetchStatus", str)
	}
	return nil
}
