// Code generated by ent, DO NOT EDIT.

package profilepost

import (
	"sheng-go-backend/ent/predicate"
	"sheng-go-backend/ent/schema/ulid"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id ulid.ID) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id ulid.ID) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id ulid.ID) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...ulid.ID) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...ulid.ID) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id ulid.ID) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id ulid.ID) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id ulid.ID) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id ulid.ID) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLTE(FieldID, id))
}

// ProfileUsername applies equality check predicate on the "profile_username" field. It's identical to ProfileUsernameEQ.
func ProfileUsername(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldProfileUsername, v))
}

// S3Key applies equality check predicate on the "s3_key" field. It's identical to S3KeyEQ.
func S3Key(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldS3Key, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProfileUsernameEQ applies the EQ predicate on the "profile_username" field.
func ProfileUsernameEQ(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldProfileUsername, v))
}

// ProfileUsernameNEQ applies the NEQ predicate on the "profile_username" field.
func ProfileUsernameNEQ(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNEQ(FieldProfileUsername, v))
}

// ProfileUsernameIn applies the In predicate on the "profile_username" field.
func ProfileUsernameIn(vs ...string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldIn(FieldProfileUsername, vs...))
}

// ProfileUsernameNotIn applies the NotIn predicate on the "profile_username" field.
func ProfileUsernameNotIn(vs ...string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNotIn(FieldProfileUsername, vs...))
}

// ProfileUsernameGT applies the GT predicate on the "profile_username" field.
func ProfileUsernameGT(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGT(FieldProfileUsername, v))
}

// ProfileUsernameGTE applies the GTE predicate on the "profile_username" field.
func ProfileUsernameGTE(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGTE(FieldProfileUsername, v))
}

// ProfileUsernameLT applies the LT predicate on the "profile_username" field.
func ProfileUsernameLT(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLT(FieldProfileUsername, v))
}

// ProfileUsernameLTE applies the LTE predicate on the "profile_username" field.
func ProfileUsernameLTE(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLTE(FieldProfileUsername, v))
}

// ProfileUsernameContains applies the Contains predicate on the "profile_username" field.
func ProfileUsernameContains(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldContains(FieldProfileUsername, v))
}

// ProfileUsernameHasPrefix applies the HasPrefix predicate on the "profile_username" field.
func ProfileUsernameHasPrefix(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldHasPrefix(FieldProfileUsername, v))
}

// ProfileUsernameHasSuffix applies the HasSuffix predicate on the "profile_username" field.
func ProfileUsernameHasSuffix(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldHasSuffix(FieldProfileUsername, v))
}

// ProfileUsernameEqualFold applies the EqualFold predicate on the "profile_username" field.
func ProfileUsernameEqualFold(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEqualFold(FieldProfileUsername, v))
}

// ProfileUsernameContainsFold applies the ContainsFold predicate on the "profile_username" field.
func ProfileUsernameContainsFold(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldContainsFold(FieldProfileUsername, v))
}

// FetchStatusEQ applies the EQ predicate on the "fetch_status" field.
func FetchStatusEQ(v FetchStatus) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldFetchStatus, v))
}

// FetchStatusNEQ applies the NEQ predicate on the "fetch_status" field.
func FetchStatusNEQ(v FetchStatus) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNEQ(FieldFetchStatus, v))
}

// FetchStatusIn applies the In predicate on the "fetch_status" field.
func FetchStatusIn(vs ...FetchStatus) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldIn(FieldFetchStatus, vs...))
}

// FetchStatusNotIn applies the NotIn predicate on the "fetch_status" field.
func FetchStatusNotIn(vs ...FetchStatus) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNotIn(FieldFetchStatus, vs...))
}

// S3KeyEQ applies the EQ predicate on the "s3_key" field.
func S3KeyEQ(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldS3Key, v))
}

// S3KeyNEQ applies the NEQ predicate on the "s3_key" field.
func S3KeyNEQ(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNEQ(FieldS3Key, v))
}

// S3KeyIn applies the In predicate on the "s3_key" field.
func S3KeyIn(vs ...string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldIn(FieldS3Key, vs...))
}

// S3KeyNotIn applies the NotIn predicate on the "s3_key" field.
func S3KeyNotIn(vs ...string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNotIn(FieldS3Key, vs...))
}

// S3KeyGT applies the GT predicate on the "s3_key" field.
func S3KeyGT(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGT(FieldS3Key, v))
}

// S3KeyGTE applies the GTE predicate on the "s3_key" field.
func S3KeyGTE(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGTE(FieldS3Key, v))
}

// S3KeyLT applies the LT predicate on the "s3_key" field.
func S3KeyLT(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLT(FieldS3Key, v))
}

// S3KeyLTE applies the LTE predicate on the "s3_key" field.
func S3KeyLTE(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLTE(FieldS3Key, v))
}

// S3KeyContains applies the Contains predicate on the "s3_key" field.
func S3KeyContains(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldContains(FieldS3Key, v))
}

// S3KeyHasPrefix applies the HasPrefix predicate on the "s3_key" field.
func S3KeyHasPrefix(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldHasPrefix(FieldS3Key, v))
}

// S3KeyHasSuffix applies the HasSuffix predicate on the "s3_key" field.
func S3KeyHasSuffix(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldHasSuffix(FieldS3Key, v))
}

// S3KeyIsNil applies the IsNil predicate on the "s3_key" field.
func S3KeyIsNil() predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldIsNull(FieldS3Key))
}

// S3KeyNotNil applies the NotNil predicate on the "s3_key" field.
func S3KeyNotNil() predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNotNull(FieldS3Key))
}

// S3KeyEqualFold applies the EqualFold predicate on the "s3_key" field.
func S3KeyEqualFold(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEqualFold(FieldS3Key, v))
}

// S3KeyContainsFold applies the ContainsFold predicate on the "s3_key" field.
func S3KeyContainsFold(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldContainsFold(FieldS3Key, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProfilePost {
	return predicate.ProfilePost(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.ProfilePost {
	return predicate.ProfilePost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.ProfilePostItem) predicate.ProfilePost {
	return predicate.ProfilePost(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProfilePost) predicate.ProfilePost {
	return predicate.ProfilePost(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProfilePost) predicate.ProfilePost {
	return predicate.ProfilePost(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProfilePost) predicate.ProfilePost {
	return predicate.ProfilePost(sql.NotPredicates(p))
}
