// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"sheng-go-backend/ent/migrate"
	"sheng-go-backend/ent/schema/ulid"

	"sheng-go-backend/ent/apiquotatracker"
	"sheng-go-backend/ent/cronjobconfig"
	"sheng-go-backend/ent/jobexecutionhistory"
	"sheng-go-backend/ent/profile"
	"sheng-go-backend/ent/profileentry"
	"sheng-go-backend/ent/todo"
	"sheng-go-backend/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// APIQuotaTracker is the client for interacting with the APIQuotaTracker builders.
	APIQuotaTracker *APIQuotaTrackerClient
	// CronJobConfig is the client for interacting with the CronJobConfig builders.
	CronJobConfig *CronJobConfigClient
	// JobExecutionHistory is the client for interacting with the JobExecutionHistory builders.
	JobExecutionHistory *JobExecutionHistoryClient
	// Profile is the client for interacting with the Profile builders.
	Profile *ProfileClient
	// ProfileEntry is the client for interacting with the ProfileEntry builders.
	ProfileEntry *ProfileEntryClient
	// Todo is the client for interacting with the Todo builders.
	Todo *TodoClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.APIQuotaTracker = NewAPIQuotaTrackerClient(c.config)
	c.CronJobConfig = NewCronJobConfigClient(c.config)
	c.JobExecutionHistory = NewJobExecutionHistoryClient(c.config)
	c.Profile = NewProfileClient(c.config)
	c.ProfileEntry = NewProfileEntryClient(c.config)
	c.Todo = NewTodoClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		APIQuotaTracker:     NewAPIQuotaTrackerClient(cfg),
		CronJobConfig:       NewCronJobConfigClient(cfg),
		JobExecutionHistory: NewJobExecutionHistoryClient(cfg),
		Profile:             NewProfileClient(cfg),
		ProfileEntry:        NewProfileEntryClient(cfg),
		Todo:                NewTodoClient(cfg),
		User:                NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		APIQuotaTracker:     NewAPIQuotaTrackerClient(cfg),
		CronJobConfig:       NewCronJobConfigClient(cfg),
		JobExecutionHistory: NewJobExecutionHistoryClient(cfg),
		Profile:             NewProfileClient(cfg),
		ProfileEntry:        NewProfileEntryClient(cfg),
		Todo:                NewTodoClient(cfg),
		User:                NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		APIQuotaTracker.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.APIQuotaTracker, c.CronJobConfig, c.JobExecutionHistory, c.Profile,
		c.ProfileEntry, c.Todo, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.APIQuotaTracker, c.CronJobConfig, c.JobExecutionHistory, c.Profile,
		c.ProfileEntry, c.Todo, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *APIQuotaTrackerMutation:
		return c.APIQuotaTracker.mutate(ctx, m)
	case *CronJobConfigMutation:
		return c.CronJobConfig.mutate(ctx, m)
	case *JobExecutionHistoryMutation:
		return c.JobExecutionHistory.mutate(ctx, m)
	case *ProfileMutation:
		return c.Profile.mutate(ctx, m)
	case *ProfileEntryMutation:
		return c.ProfileEntry.mutate(ctx, m)
	case *TodoMutation:
		return c.Todo.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// APIQuotaTrackerClient is a client for the APIQuotaTracker schema.
type APIQuotaTrackerClient struct {
	config
}

// NewAPIQuotaTrackerClient returns a client for the APIQuotaTracker from the given config.
func NewAPIQuotaTrackerClient(c config) *APIQuotaTrackerClient {
	return &APIQuotaTrackerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `apiquotatracker.Hooks(f(g(h())))`.
func (c *APIQuotaTrackerClient) Use(hooks ...Hook) {
	c.hooks.APIQuotaTracker = append(c.hooks.APIQuotaTracker, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `apiquotatracker.Intercept(f(g(h())))`.
func (c *APIQuotaTrackerClient) Intercept(interceptors ...Interceptor) {
	c.inters.APIQuotaTracker = append(c.inters.APIQuotaTracker, interceptors...)
}

// Create returns a builder for creating a APIQuotaTracker entity.
func (c *APIQuotaTrackerClient) Create() *APIQuotaTrackerCreate {
	mutation := newAPIQuotaTrackerMutation(c.config, OpCreate)
	return &APIQuotaTrackerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of APIQuotaTracker entities.
func (c *APIQuotaTrackerClient) CreateBulk(builders ...*APIQuotaTrackerCreate) *APIQuotaTrackerCreateBulk {
	return &APIQuotaTrackerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *APIQuotaTrackerClient) MapCreateBulk(slice any, setFunc func(*APIQuotaTrackerCreate, int)) *APIQuotaTrackerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &APIQuotaTrackerCreateBulk{err: fmt.Errorf("calling to APIQuotaTrackerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*APIQuotaTrackerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &APIQuotaTrackerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for APIQuotaTracker.
func (c *APIQuotaTrackerClient) Update() *APIQuotaTrackerUpdate {
	mutation := newAPIQuotaTrackerMutation(c.config, OpUpdate)
	return &APIQuotaTrackerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *APIQuotaTrackerClient) UpdateOne(aqt *APIQuotaTracker) *APIQuotaTrackerUpdateOne {
	mutation := newAPIQuotaTrackerMutation(c.config, OpUpdateOne, withAPIQuotaTracker(aqt))
	return &APIQuotaTrackerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *APIQuotaTrackerClient) UpdateOneID(id ulid.ID) *APIQuotaTrackerUpdateOne {
	mutation := newAPIQuotaTrackerMutation(c.config, OpUpdateOne, withAPIQuotaTrackerID(id))
	return &APIQuotaTrackerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for APIQuotaTracker.
func (c *APIQuotaTrackerClient) Delete() *APIQuotaTrackerDelete {
	mutation := newAPIQuotaTrackerMutation(c.config, OpDelete)
	return &APIQuotaTrackerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *APIQuotaTrackerClient) DeleteOne(aqt *APIQuotaTracker) *APIQuotaTrackerDeleteOne {
	return c.DeleteOneID(aqt.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *APIQuotaTrackerClient) DeleteOneID(id ulid.ID) *APIQuotaTrackerDeleteOne {
	builder := c.Delete().Where(apiquotatracker.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &APIQuotaTrackerDeleteOne{builder}
}

// Query returns a query builder for APIQuotaTracker.
func (c *APIQuotaTrackerClient) Query() *APIQuotaTrackerQuery {
	return &APIQuotaTrackerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAPIQuotaTracker},
		inters: c.Interceptors(),
	}
}

// Get returns a APIQuotaTracker entity by its id.
func (c *APIQuotaTrackerClient) Get(ctx context.Context, id ulid.ID) (*APIQuotaTracker, error) {
	return c.Query().Where(apiquotatracker.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *APIQuotaTrackerClient) GetX(ctx context.Context, id ulid.ID) *APIQuotaTracker {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *APIQuotaTrackerClient) Hooks() []Hook {
	return c.hooks.APIQuotaTracker
}

// Interceptors returns the client interceptors.
func (c *APIQuotaTrackerClient) Interceptors() []Interceptor {
	return c.inters.APIQuotaTracker
}

func (c *APIQuotaTrackerClient) mutate(ctx context.Context, m *APIQuotaTrackerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&APIQuotaTrackerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&APIQuotaTrackerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&APIQuotaTrackerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&APIQuotaTrackerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown APIQuotaTracker mutation op: %q", m.Op())
	}
}

// CronJobConfigClient is a client for the CronJobConfig schema.
type CronJobConfigClient struct {
	config
}

// NewCronJobConfigClient returns a client for the CronJobConfig from the given config.
func NewCronJobConfigClient(c config) *CronJobConfigClient {
	return &CronJobConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cronjobconfig.Hooks(f(g(h())))`.
func (c *CronJobConfigClient) Use(hooks ...Hook) {
	c.hooks.CronJobConfig = append(c.hooks.CronJobConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `cronjobconfig.Intercept(f(g(h())))`.
func (c *CronJobConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.CronJobConfig = append(c.inters.CronJobConfig, interceptors...)
}

// Create returns a builder for creating a CronJobConfig entity.
func (c *CronJobConfigClient) Create() *CronJobConfigCreate {
	mutation := newCronJobConfigMutation(c.config, OpCreate)
	return &CronJobConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CronJobConfig entities.
func (c *CronJobConfigClient) CreateBulk(builders ...*CronJobConfigCreate) *CronJobConfigCreateBulk {
	return &CronJobConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CronJobConfigClient) MapCreateBulk(slice any, setFunc func(*CronJobConfigCreate, int)) *CronJobConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CronJobConfigCreateBulk{err: fmt.Errorf("calling to CronJobConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CronJobConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CronJobConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CronJobConfig.
func (c *CronJobConfigClient) Update() *CronJobConfigUpdate {
	mutation := newCronJobConfigMutation(c.config, OpUpdate)
	return &CronJobConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CronJobConfigClient) UpdateOne(cjc *CronJobConfig) *CronJobConfigUpdateOne {
	mutation := newCronJobConfigMutation(c.config, OpUpdateOne, withCronJobConfig(cjc))
	return &CronJobConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CronJobConfigClient) UpdateOneID(id ulid.ID) *CronJobConfigUpdateOne {
	mutation := newCronJobConfigMutation(c.config, OpUpdateOne, withCronJobConfigID(id))
	return &CronJobConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CronJobConfig.
func (c *CronJobConfigClient) Delete() *CronJobConfigDelete {
	mutation := newCronJobConfigMutation(c.config, OpDelete)
	return &CronJobConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CronJobConfigClient) DeleteOne(cjc *CronJobConfig) *CronJobConfigDeleteOne {
	return c.DeleteOneID(cjc.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CronJobConfigClient) DeleteOneID(id ulid.ID) *CronJobConfigDeleteOne {
	builder := c.Delete().Where(cronjobconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CronJobConfigDeleteOne{builder}
}

// Query returns a query builder for CronJobConfig.
func (c *CronJobConfigClient) Query() *CronJobConfigQuery {
	return &CronJobConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCronJobConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a CronJobConfig entity by its id.
func (c *CronJobConfigClient) Get(ctx context.Context, id ulid.ID) (*CronJobConfig, error) {
	return c.Query().Where(cronjobconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CronJobConfigClient) GetX(ctx context.Context, id ulid.ID) *CronJobConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CronJobConfigClient) Hooks() []Hook {
	return c.hooks.CronJobConfig
}

// Interceptors returns the client interceptors.
func (c *CronJobConfigClient) Interceptors() []Interceptor {
	return c.inters.CronJobConfig
}

func (c *CronJobConfigClient) mutate(ctx context.Context, m *CronJobConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CronJobConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CronJobConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CronJobConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CronJobConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CronJobConfig mutation op: %q", m.Op())
	}
}

// JobExecutionHistoryClient is a client for the JobExecutionHistory schema.
type JobExecutionHistoryClient struct {
	config
}

// NewJobExecutionHistoryClient returns a client for the JobExecutionHistory from the given config.
func NewJobExecutionHistoryClient(c config) *JobExecutionHistoryClient {
	return &JobExecutionHistoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `jobexecutionhistory.Hooks(f(g(h())))`.
func (c *JobExecutionHistoryClient) Use(hooks ...Hook) {
	c.hooks.JobExecutionHistory = append(c.hooks.JobExecutionHistory, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `jobexecutionhistory.Intercept(f(g(h())))`.
func (c *JobExecutionHistoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.JobExecutionHistory = append(c.inters.JobExecutionHistory, interceptors...)
}

// Create returns a builder for creating a JobExecutionHistory entity.
func (c *JobExecutionHistoryClient) Create() *JobExecutionHistoryCreate {
	mutation := newJobExecutionHistoryMutation(c.config, OpCreate)
	return &JobExecutionHistoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of JobExecutionHistory entities.
func (c *JobExecutionHistoryClient) CreateBulk(builders ...*JobExecutionHistoryCreate) *JobExecutionHistoryCreateBulk {
	return &JobExecutionHistoryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *JobExecutionHistoryClient) MapCreateBulk(slice any, setFunc func(*JobExecutionHistoryCreate, int)) *JobExecutionHistoryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &JobExecutionHistoryCreateBulk{err: fmt.Errorf("calling to JobExecutionHistoryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*JobExecutionHistoryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &JobExecutionHistoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for JobExecutionHistory.
func (c *JobExecutionHistoryClient) Update() *JobExecutionHistoryUpdate {
	mutation := newJobExecutionHistoryMutation(c.config, OpUpdate)
	return &JobExecutionHistoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *JobExecutionHistoryClient) UpdateOne(jeh *JobExecutionHistory) *JobExecutionHistoryUpdateOne {
	mutation := newJobExecutionHistoryMutation(c.config, OpUpdateOne, withJobExecutionHistory(jeh))
	return &JobExecutionHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *JobExecutionHistoryClient) UpdateOneID(id ulid.ID) *JobExecutionHistoryUpdateOne {
	mutation := newJobExecutionHistoryMutation(c.config, OpUpdateOne, withJobExecutionHistoryID(id))
	return &JobExecutionHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for JobExecutionHistory.
func (c *JobExecutionHistoryClient) Delete() *JobExecutionHistoryDelete {
	mutation := newJobExecutionHistoryMutation(c.config, OpDelete)
	return &JobExecutionHistoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *JobExecutionHistoryClient) DeleteOne(jeh *JobExecutionHistory) *JobExecutionHistoryDeleteOne {
	return c.DeleteOneID(jeh.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *JobExecutionHistoryClient) DeleteOneID(id ulid.ID) *JobExecutionHistoryDeleteOne {
	builder := c.Delete().Where(jobexecutionhistory.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &JobExecutionHistoryDeleteOne{builder}
}

// Query returns a query builder for JobExecutionHistory.
func (c *JobExecutionHistoryClient) Query() *JobExecutionHistoryQuery {
	return &JobExecutionHistoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeJobExecutionHistory},
		inters: c.Interceptors(),
	}
}

// Get returns a JobExecutionHistory entity by its id.
func (c *JobExecutionHistoryClient) Get(ctx context.Context, id ulid.ID) (*JobExecutionHistory, error) {
	return c.Query().Where(jobexecutionhistory.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *JobExecutionHistoryClient) GetX(ctx context.Context, id ulid.ID) *JobExecutionHistory {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *JobExecutionHistoryClient) Hooks() []Hook {
	return c.hooks.JobExecutionHistory
}

// Interceptors returns the client interceptors.
func (c *JobExecutionHistoryClient) Interceptors() []Interceptor {
	return c.inters.JobExecutionHistory
}

func (c *JobExecutionHistoryClient) mutate(ctx context.Context, m *JobExecutionHistoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&JobExecutionHistoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&JobExecutionHistoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&JobExecutionHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&JobExecutionHistoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown JobExecutionHistory mutation op: %q", m.Op())
	}
}

// ProfileClient is a client for the Profile schema.
type ProfileClient struct {
	config
}

// NewProfileClient returns a client for the Profile from the given config.
func NewProfileClient(c config) *ProfileClient {
	return &ProfileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `profile.Hooks(f(g(h())))`.
func (c *ProfileClient) Use(hooks ...Hook) {
	c.hooks.Profile = append(c.hooks.Profile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `profile.Intercept(f(g(h())))`.
func (c *ProfileClient) Intercept(interceptors ...Interceptor) {
	c.inters.Profile = append(c.inters.Profile, interceptors...)
}

// Create returns a builder for creating a Profile entity.
func (c *ProfileClient) Create() *ProfileCreate {
	mutation := newProfileMutation(c.config, OpCreate)
	return &ProfileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Profile entities.
func (c *ProfileClient) CreateBulk(builders ...*ProfileCreate) *ProfileCreateBulk {
	return &ProfileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProfileClient) MapCreateBulk(slice any, setFunc func(*ProfileCreate, int)) *ProfileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProfileCreateBulk{err: fmt.Errorf("calling to ProfileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProfileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProfileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Profile.
func (c *ProfileClient) Update() *ProfileUpdate {
	mutation := newProfileMutation(c.config, OpUpdate)
	return &ProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProfileClient) UpdateOne(pr *Profile) *ProfileUpdateOne {
	mutation := newProfileMutation(c.config, OpUpdateOne, withProfile(pr))
	return &ProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProfileClient) UpdateOneID(id ulid.ID) *ProfileUpdateOne {
	mutation := newProfileMutation(c.config, OpUpdateOne, withProfileID(id))
	return &ProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Profile.
func (c *ProfileClient) Delete() *ProfileDelete {
	mutation := newProfileMutation(c.config, OpDelete)
	return &ProfileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProfileClient) DeleteOne(pr *Profile) *ProfileDeleteOne {
	return c.DeleteOneID(pr.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProfileClient) DeleteOneID(id ulid.ID) *ProfileDeleteOne {
	builder := c.Delete().Where(profile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProfileDeleteOne{builder}
}

// Query returns a query builder for Profile.
func (c *ProfileClient) Query() *ProfileQuery {
	return &ProfileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProfile},
		inters: c.Interceptors(),
	}
}

// Get returns a Profile entity by its id.
func (c *ProfileClient) Get(ctx context.Context, id ulid.ID) (*Profile, error) {
	return c.Query().Where(profile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProfileClient) GetX(ctx context.Context, id ulid.ID) *Profile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProfileEntry queries the profile_entry edge of a Profile.
func (c *ProfileClient) QueryProfileEntry(pr *Profile) *ProfileEntryQuery {
	query := (&ProfileEntryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(profile.Table, profile.FieldID, id),
			sqlgraph.To(profileentry.Table, profileentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, profile.ProfileEntryTable, profile.ProfileEntryColumn),
		)
		fromV = sqlgraph.Neighbors(pr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProfileClient) Hooks() []Hook {
	return c.hooks.Profile
}

// Interceptors returns the client interceptors.
func (c *ProfileClient) Interceptors() []Interceptor {
	return c.inters.Profile
}

func (c *ProfileClient) mutate(ctx context.Context, m *ProfileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProfileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProfileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Profile mutation op: %q", m.Op())
	}
}

// ProfileEntryClient is a client for the ProfileEntry schema.
type ProfileEntryClient struct {
	config
}

// NewProfileEntryClient returns a client for the ProfileEntry from the given config.
func NewProfileEntryClient(c config) *ProfileEntryClient {
	return &ProfileEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `profileentry.Hooks(f(g(h())))`.
func (c *ProfileEntryClient) Use(hooks ...Hook) {
	c.hooks.ProfileEntry = append(c.hooks.ProfileEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `profileentry.Intercept(f(g(h())))`.
func (c *ProfileEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProfileEntry = append(c.inters.ProfileEntry, interceptors...)
}

// Create returns a builder for creating a ProfileEntry entity.
func (c *ProfileEntryClient) Create() *ProfileEntryCreate {
	mutation := newProfileEntryMutation(c.config, OpCreate)
	return &ProfileEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProfileEntry entities.
func (c *ProfileEntryClient) CreateBulk(builders ...*ProfileEntryCreate) *ProfileEntryCreateBulk {
	return &ProfileEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProfileEntryClient) MapCreateBulk(slice any, setFunc func(*ProfileEntryCreate, int)) *ProfileEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProfileEntryCreateBulk{err: fmt.Errorf("calling to ProfileEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProfileEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProfileEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProfileEntry.
func (c *ProfileEntryClient) Update() *ProfileEntryUpdate {
	mutation := newProfileEntryMutation(c.config, OpUpdate)
	return &ProfileEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProfileEntryClient) UpdateOne(pe *ProfileEntry) *ProfileEntryUpdateOne {
	mutation := newProfileEntryMutation(c.config, OpUpdateOne, withProfileEntry(pe))
	return &ProfileEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProfileEntryClient) UpdateOneID(id ulid.ID) *ProfileEntryUpdateOne {
	mutation := newProfileEntryMutation(c.config, OpUpdateOne, withProfileEntryID(id))
	return &ProfileEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProfileEntry.
func (c *ProfileEntryClient) Delete() *ProfileEntryDelete {
	mutation := newProfileEntryMutation(c.config, OpDelete)
	return &ProfileEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProfileEntryClient) DeleteOne(pe *ProfileEntry) *ProfileEntryDeleteOne {
	return c.DeleteOneID(pe.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProfileEntryClient) DeleteOneID(id ulid.ID) *ProfileEntryDeleteOne {
	builder := c.Delete().Where(profileentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProfileEntryDeleteOne{builder}
}

// Query returns a query builder for ProfileEntry.
func (c *ProfileEntryClient) Query() *ProfileEntryQuery {
	return &ProfileEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProfileEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a ProfileEntry entity by its id.
func (c *ProfileEntryClient) Get(ctx context.Context, id ulid.ID) (*ProfileEntry, error) {
	return c.Query().Where(profileentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProfileEntryClient) GetX(ctx context.Context, id ulid.ID) *ProfileEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProfile queries the profile edge of a ProfileEntry.
func (c *ProfileEntryClient) QueryProfile(pe *ProfileEntry) *ProfileQuery {
	query := (&ProfileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pe.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(profileentry.Table, profileentry.FieldID, id),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, profileentry.ProfileTable, profileentry.ProfileColumn),
		)
		fromV = sqlgraph.Neighbors(pe.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProfileEntryClient) Hooks() []Hook {
	return c.hooks.ProfileEntry
}

// Interceptors returns the client interceptors.
func (c *ProfileEntryClient) Interceptors() []Interceptor {
	return c.inters.ProfileEntry
}

func (c *ProfileEntryClient) mutate(ctx context.Context, m *ProfileEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProfileEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProfileEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProfileEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProfileEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ProfileEntry mutation op: %q", m.Op())
	}
}

// TodoClient is a client for the Todo schema.
type TodoClient struct {
	config
}

// NewTodoClient returns a client for the Todo from the given config.
func NewTodoClient(c config) *TodoClient {
	return &TodoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `todo.Hooks(f(g(h())))`.
func (c *TodoClient) Use(hooks ...Hook) {
	c.hooks.Todo = append(c.hooks.Todo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `todo.Intercept(f(g(h())))`.
func (c *TodoClient) Intercept(interceptors ...Interceptor) {
	c.inters.Todo = append(c.inters.Todo, interceptors...)
}

// Create returns a builder for creating a Todo entity.
func (c *TodoClient) Create() *TodoCreate {
	mutation := newTodoMutation(c.config, OpCreate)
	return &TodoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Todo entities.
func (c *TodoClient) CreateBulk(builders ...*TodoCreate) *TodoCreateBulk {
	return &TodoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TodoClient) MapCreateBulk(slice any, setFunc func(*TodoCreate, int)) *TodoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TodoCreateBulk{err: fmt.Errorf("calling to TodoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TodoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TodoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Todo.
func (c *TodoClient) Update() *TodoUpdate {
	mutation := newTodoMutation(c.config, OpUpdate)
	return &TodoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TodoClient) UpdateOne(t *Todo) *TodoUpdateOne {
	mutation := newTodoMutation(c.config, OpUpdateOne, withTodo(t))
	return &TodoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TodoClient) UpdateOneID(id ulid.ID) *TodoUpdateOne {
	mutation := newTodoMutation(c.config, OpUpdateOne, withTodoID(id))
	return &TodoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Todo.
func (c *TodoClient) Delete() *TodoDelete {
	mutation := newTodoMutation(c.config, OpDelete)
	return &TodoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TodoClient) DeleteOne(t *Todo) *TodoDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TodoClient) DeleteOneID(id ulid.ID) *TodoDeleteOne {
	builder := c.Delete().Where(todo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TodoDeleteOne{builder}
}

// Query returns a query builder for Todo.
func (c *TodoClient) Query() *TodoQuery {
	return &TodoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTodo},
		inters: c.Interceptors(),
	}
}

// Get returns a Todo entity by its id.
func (c *TodoClient) Get(ctx context.Context, id ulid.ID) (*Todo, error) {
	return c.Query().Where(todo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TodoClient) GetX(ctx context.Context, id ulid.ID) *Todo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Todo.
func (c *TodoClient) QueryUser(t *Todo) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(todo.Table, todo.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, todo.UserTable, todo.UserColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TodoClient) Hooks() []Hook {
	return c.hooks.Todo
}

// Interceptors returns the client interceptors.
func (c *TodoClient) Interceptors() []Interceptor {
	return c.inters.Todo
}

func (c *TodoClient) mutate(ctx context.Context, m *TodoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TodoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TodoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TodoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TodoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Todo mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id ulid.ID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id ulid.ID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id ulid.ID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id ulid.ID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTodos queries the todos edge of a User.
func (c *UserClient) QueryTodos(u *User) *TodoQuery {
	query := (&TodoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(todo.Table, todo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.TodosTable, user.TodosColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		APIQuotaTracker, CronJobConfig, JobExecutionHistory, Profile, ProfileEntry,
		Todo, User []ent.Hook
	}
	inters struct {
		APIQuotaTracker, CronJobConfig, JobExecutionHistory, Profile, ProfileEntry,
		Todo, User []ent.Interceptor
	}
)
