// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sheng-go-backend/ent/profileentry"
	"sheng-go-backend/ent/schema/ulid"
	"sheng-go-backend/ent/todo"
	"time"
)

// CreateProfileInput represents a mutation input for creating profiles.
type CreateProfileInput struct {
	Name       string
	Title      string
	Urn        string
	SourceFile string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
	TodoIDs    []ulid.ID
}

// Mutate applies the CreateProfileInput on the ProfileCreate builder.
func (i *CreateProfileInput) Mutate(m *ProfileCreate) {
	m.SetName(i.Name)
	m.SetTitle(i.Title)
	m.SetUrn(i.Urn)
	m.SetSourceFile(i.SourceFile)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if ids := i.TodoIDs; len(ids) > 0 {
		m.AddTodoIDs(ids...)
	}
}

// SetInput applies the change-set in the CreateProfileInput on the create builder.
func (c *ProfileCreate) SetInput(i CreateProfileInput) *ProfileCreate {
	i.Mutate(c)
	return c
}

// UpdateProfileInput represents a mutation input for updating profiles.
type UpdateProfileInput struct {
	ID            ulid.ID
	Name          *string
	Title         *string
	Urn           *string
	SourceFile    *string
	UpdatedAt     *time.Time
	AddTodoIDs    []ulid.ID
	RemoveTodoIDs []ulid.ID
}

// Mutate applies the UpdateProfileInput on the ProfileMutation.
func (i *UpdateProfileInput) Mutate(m *ProfileMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Title; v != nil {
		m.SetTitle(*v)
	}
	if v := i.Urn; v != nil {
		m.SetUrn(*v)
	}
	if v := i.SourceFile; v != nil {
		m.SetSourceFile(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if ids := i.AddTodoIDs; len(ids) > 0 {
		m.AddTodoIDs(ids...)
	}
	if ids := i.RemoveTodoIDs; len(ids) > 0 {
		m.RemoveTodoIDs(ids...)
	}
}

// SetInput applies the change-set in the UpdateProfileInput on the update builder.
func (u *ProfileUpdate) SetInput(i UpdateProfileInput) *ProfileUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateProfileInput on the update-one builder.
func (u *ProfileUpdateOne) SetInput(i UpdateProfileInput) *ProfileUpdateOne {
	i.Mutate(u.Mutation())
	return u
}

// CreateProfileEntryInput represents a mutation input for creating profileentries.
type CreateProfileEntryInput struct {
	CreatedAt         *time.Time
	UpdatedAt         *time.Time
	LinkedinUrn       string
	Gender            *string
	Status            *profileentry.Status
	ProfileData       *map[string]interface{}
	TemplateJSONS3Key *string
	RawResponseS3Key  *string
	FetchCount        *int
	LastFetchedAt     *time.Time
	ErrorMessage      *string
}

// Mutate applies the CreateProfileEntryInput on the ProfileEntryCreate builder.
func (i *CreateProfileEntryInput) Mutate(m *ProfileEntryCreate) {
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	m.SetLinkedinUrn(i.LinkedinUrn)
	if v := i.Gender; v != nil {
		m.SetGender(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.ProfileData; v != nil {
		m.SetProfileData(*v)
	}
	if v := i.TemplateJSONS3Key; v != nil {
		m.SetTemplateJSONS3Key(*v)
	}
	if v := i.RawResponseS3Key; v != nil {
		m.SetRawResponseS3Key(*v)
	}
	if v := i.FetchCount; v != nil {
		m.SetFetchCount(*v)
	}
	if v := i.LastFetchedAt; v != nil {
		m.SetLastFetchedAt(*v)
	}
	if v := i.ErrorMessage; v != nil {
		m.SetErrorMessage(*v)
	}
}

// SetInput applies the change-set in the CreateProfileEntryInput on the create builder.
func (c *ProfileEntryCreate) SetInput(i CreateProfileEntryInput) *ProfileEntryCreate {
	i.Mutate(c)
	return c
}

// UpdateProfileEntryInput represents a mutation input for updating profileentries.
type UpdateProfileEntryInput struct {
	ID                     ulid.ID
	UpdatedAt              *time.Time
	LinkedinUrn            *string
	Gender                 *string
	ClearGender            bool
	Status                 *profileentry.Status
	ProfileData            *map[string]interface{}
	ClearProfileData       bool
	TemplateJSONS3Key      *string
	ClearTemplateJSONS3Key bool
	RawResponseS3Key       *string
	ClearRawResponseS3Key  bool
	FetchCount             *int
	LastFetchedAt          *time.Time
	ClearLastFetchedAt     bool
	ErrorMessage           *string
	ClearErrorMessage      bool
}

// Mutate applies the UpdateProfileEntryInput on the ProfileEntryMutation.
func (i *UpdateProfileEntryInput) Mutate(m *ProfileEntryMutation) {
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.LinkedinUrn; v != nil {
		m.SetLinkedinUrn(*v)
	}
	if i.ClearGender {
		m.ClearGender()
	}
	if v := i.Gender; v != nil {
		m.SetGender(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if i.ClearProfileData {
		m.ClearProfileData()
	}
	if v := i.ProfileData; v != nil {
		m.SetProfileData(*v)
	}
	if i.ClearTemplateJSONS3Key {
		m.ClearTemplateJSONS3Key()
	}
	if v := i.TemplateJSONS3Key; v != nil {
		m.SetTemplateJSONS3Key(*v)
	}
	if i.ClearRawResponseS3Key {
		m.ClearRawResponseS3Key()
	}
	if v := i.RawResponseS3Key; v != nil {
		m.SetRawResponseS3Key(*v)
	}
	if v := i.FetchCount; v != nil {
		m.SetFetchCount(*v)
	}
	if i.ClearLastFetchedAt {
		m.ClearLastFetchedAt()
	}
	if v := i.LastFetchedAt; v != nil {
		m.SetLastFetchedAt(*v)
	}
	if i.ClearErrorMessage {
		m.ClearErrorMessage()
	}
	if v := i.ErrorMessage; v != nil {
		m.SetErrorMessage(*v)
	}
}

// SetInput applies the change-set in the UpdateProfileEntryInput on the update builder.
func (u *ProfileEntryUpdate) SetInput(i UpdateProfileEntryInput) *ProfileEntryUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateProfileEntryInput on the update-one builder.
func (u *ProfileEntryUpdateOne) SetInput(i UpdateProfileEntryInput) *ProfileEntryUpdateOne {
	i.Mutate(u.Mutation())
	return u
}

// CreateTodoInput represents a mutation input for creating todos.
type CreateTodoInput struct {
	Name      *string
	Status    *todo.Status
	Priority  *int
	CreatedAt *time.Time
	UpdatedAt *time.Time
	UserID    *ulid.ID
}

// Mutate applies the CreateTodoInput on the TodoCreate builder.
func (i *CreateTodoInput) Mutate(m *TodoCreate) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Priority; v != nil {
		m.SetPriority(*v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.UserID; v != nil {
		m.SetUserID(*v)
	}
}

// SetInput applies the change-set in the CreateTodoInput on the create builder.
func (c *TodoCreate) SetInput(i CreateTodoInput) *TodoCreate {
	i.Mutate(c)
	return c
}

// UpdateTodoInput represents a mutation input for updating todos.
type UpdateTodoInput struct {
	ID        ulid.ID
	Name      *string
	Status    *todo.Status
	Priority  *int
	UpdatedAt *time.Time
	UserID    *ulid.ID
	ClearUser bool
}

// Mutate applies the UpdateTodoInput on the TodoMutation.
func (i *UpdateTodoInput) Mutate(m *TodoMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Priority; v != nil {
		m.SetPriority(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if i.ClearUser {
		m.ClearUser()
	}
	if v := i.UserID; v != nil {
		m.SetUserID(*v)
	}
}

// SetInput applies the change-set in the UpdateTodoInput on the update builder.
func (u *TodoUpdate) SetInput(i UpdateTodoInput) *TodoUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateTodoInput on the update-one builder.
func (u *TodoUpdateOne) SetInput(i UpdateTodoInput) *TodoUpdateOne {
	i.Mutate(u.Mutation())
	return u
}

// CreateUserInput represents a mutation input for creating users.
type CreateUserInput struct {
	Name      string
	Age       int
	Email     string
	Password  string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	TodoIDs   []ulid.ID
}

// Mutate applies the CreateUserInput on the UserCreate builder.
func (i *CreateUserInput) Mutate(m *UserCreate) {
	m.SetName(i.Name)
	m.SetAge(i.Age)
	m.SetEmail(i.Email)
	m.SetPassword(i.Password)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if ids := i.TodoIDs; len(ids) > 0 {
		m.AddTodoIDs(ids...)
	}
}

// SetInput applies the change-set in the CreateUserInput on the create builder.
func (c *UserCreate) SetInput(i CreateUserInput) *UserCreate {
	i.Mutate(c)
	return c
}

// UpdateUserInput represents a mutation input for updating users.
type UpdateUserInput struct {
	ID            ulid.ID
	Name          *string
	Age           *int
	Email         *string
	Password      *string
	UpdatedAt     *time.Time
	AddTodoIDs    []ulid.ID
	RemoveTodoIDs []ulid.ID
}

// Mutate applies the UpdateUserInput on the UserMutation.
func (i *UpdateUserInput) Mutate(m *UserMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Age; v != nil {
		m.SetAge(*v)
	}
	if v := i.Email; v != nil {
		m.SetEmail(*v)
	}
	if v := i.Password; v != nil {
		m.SetPassword(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if ids := i.AddTodoIDs; len(ids) > 0 {
		m.AddTodoIDs(ids...)
	}
	if ids := i.RemoveTodoIDs; len(ids) > 0 {
		m.RemoveTodoIDs(ids...)
	}
}

// SetInput applies the change-set in the UpdateUserInput on the update builder.
func (u *UserUpdate) SetInput(i UpdateUserInput) *UserUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateUserInput on the update-one builder.
func (u *UserUpdateOne) SetInput(i UpdateUserInput) *UserUpdateOne {
	i.Mutate(u.Mutation())
	return u
}
