// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sheng-go-backend/ent/cronjobconfig"
	"sheng-go-backend/ent/jobexecutionhistory"
	"sheng-go-backend/ent/profileentry"
	"sheng-go-backend/ent/schema/ulid"
	"sheng-go-backend/ent/todo"
	"time"
)

// CreateAPIQuotaTrackerInput represents a mutation input for creating apiquotatrackers.
type CreateAPIQuotaTrackerInput struct {
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	Month            int
	Year             int
	CallCount        *int
	QuotaLimit       *int
	QuotaExceeded    *bool
	OverrideEnabled  *bool
	NotificationSent *bool
	LastCallAt       *time.Time
}

// Mutate applies the CreateAPIQuotaTrackerInput on the APIQuotaTrackerCreate builder.
func (i *CreateAPIQuotaTrackerInput) Mutate(m *APIQuotaTrackerCreate) {
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	m.SetMonth(i.Month)
	m.SetYear(i.Year)
	if v := i.CallCount; v != nil {
		m.SetCallCount(*v)
	}
	if v := i.QuotaLimit; v != nil {
		m.SetQuotaLimit(*v)
	}
	if v := i.QuotaExceeded; v != nil {
		m.SetQuotaExceeded(*v)
	}
	if v := i.OverrideEnabled; v != nil {
		m.SetOverrideEnabled(*v)
	}
	if v := i.NotificationSent; v != nil {
		m.SetNotificationSent(*v)
	}
	if v := i.LastCallAt; v != nil {
		m.SetLastCallAt(*v)
	}
}

// SetInput applies the change-set in the CreateAPIQuotaTrackerInput on the create builder.
func (c *APIQuotaTrackerCreate) SetInput(i CreateAPIQuotaTrackerInput) *APIQuotaTrackerCreate {
	i.Mutate(c)
	return c
}

// UpdateAPIQuotaTrackerInput represents a mutation input for updating apiquotatrackers.
type UpdateAPIQuotaTrackerInput struct {
	ID               ulid.ID
	UpdatedAt        *time.Time
	Month            *int
	Year             *int
	CallCount        *int
	QuotaLimit       *int
	QuotaExceeded    *bool
	OverrideEnabled  *bool
	NotificationSent *bool
	LastCallAt       *time.Time
	ClearLastCallAt  bool
}

// Mutate applies the UpdateAPIQuotaTrackerInput on the APIQuotaTrackerMutation.
func (i *UpdateAPIQuotaTrackerInput) Mutate(m *APIQuotaTrackerMutation) {
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.Month; v != nil {
		m.SetMonth(*v)
	}
	if v := i.Year; v != nil {
		m.SetYear(*v)
	}
	if v := i.CallCount; v != nil {
		m.SetCallCount(*v)
	}
	if v := i.QuotaLimit; v != nil {
		m.SetQuotaLimit(*v)
	}
	if v := i.QuotaExceeded; v != nil {
		m.SetQuotaExceeded(*v)
	}
	if v := i.OverrideEnabled; v != nil {
		m.SetOverrideEnabled(*v)
	}
	if v := i.NotificationSent; v != nil {
		m.SetNotificationSent(*v)
	}
	if i.ClearLastCallAt {
		m.ClearLastCallAt()
	}
	if v := i.LastCallAt; v != nil {
		m.SetLastCallAt(*v)
	}
}

// SetInput applies the change-set in the UpdateAPIQuotaTrackerInput on the update builder.
func (u *APIQuotaTrackerUpdate) SetInput(i UpdateAPIQuotaTrackerInput) *APIQuotaTrackerUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateAPIQuotaTrackerInput on the update-one builder.
func (u *APIQuotaTrackerUpdateOne) SetInput(i UpdateAPIQuotaTrackerInput) *APIQuotaTrackerUpdateOne {
	i.Mutate(u.Mutation())
	return u
}

// CreateCronJobConfigInput represents a mutation input for creating cronjobconfigs.
type CreateCronJobConfigInput struct {
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	JobName      string
	JobType      cronjobconfig.JobType
	Schedule     string
	Enabled      *bool
	BatchSize    *int
	AdminEmail   string
	RespectQuota *bool
	LastRunAt    *time.Time
	NextRunAt    *time.Time
}

// Mutate applies the CreateCronJobConfigInput on the CronJobConfigCreate builder.
func (i *CreateCronJobConfigInput) Mutate(m *CronJobConfigCreate) {
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	m.SetJobName(i.JobName)
	m.SetJobType(i.JobType)
	m.SetSchedule(i.Schedule)
	if v := i.Enabled; v != nil {
		m.SetEnabled(*v)
	}
	if v := i.BatchSize; v != nil {
		m.SetBatchSize(*v)
	}
	m.SetAdminEmail(i.AdminEmail)
	if v := i.RespectQuota; v != nil {
		m.SetRespectQuota(*v)
	}
	if v := i.LastRunAt; v != nil {
		m.SetLastRunAt(*v)
	}
	if v := i.NextRunAt; v != nil {
		m.SetNextRunAt(*v)
	}
}

// SetInput applies the change-set in the CreateCronJobConfigInput on the create builder.
func (c *CronJobConfigCreate) SetInput(i CreateCronJobConfigInput) *CronJobConfigCreate {
	i.Mutate(c)
	return c
}

// UpdateCronJobConfigInput represents a mutation input for updating cronjobconfigs.
type UpdateCronJobConfigInput struct {
	ID             ulid.ID
	UpdatedAt      *time.Time
	JobName        *string
	JobType        *cronjobconfig.JobType
	Schedule       *string
	Enabled        *bool
	BatchSize      *int
	AdminEmail     *string
	RespectQuota   *bool
	LastRunAt      *time.Time
	ClearLastRunAt bool
	NextRunAt      *time.Time
	ClearNextRunAt bool
}

// Mutate applies the UpdateCronJobConfigInput on the CronJobConfigMutation.
func (i *UpdateCronJobConfigInput) Mutate(m *CronJobConfigMutation) {
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.JobName; v != nil {
		m.SetJobName(*v)
	}
	if v := i.JobType; v != nil {
		m.SetJobType(*v)
	}
	if v := i.Schedule; v != nil {
		m.SetSchedule(*v)
	}
	if v := i.Enabled; v != nil {
		m.SetEnabled(*v)
	}
	if v := i.BatchSize; v != nil {
		m.SetBatchSize(*v)
	}
	if v := i.AdminEmail; v != nil {
		m.SetAdminEmail(*v)
	}
	if v := i.RespectQuota; v != nil {
		m.SetRespectQuota(*v)
	}
	if i.ClearLastRunAt {
		m.ClearLastRunAt()
	}
	if v := i.LastRunAt; v != nil {
		m.SetLastRunAt(*v)
	}
	if i.ClearNextRunAt {
		m.ClearNextRunAt()
	}
	if v := i.NextRunAt; v != nil {
		m.SetNextRunAt(*v)
	}
}

// SetInput applies the change-set in the UpdateCronJobConfigInput on the update builder.
func (u *CronJobConfigUpdate) SetInput(i UpdateCronJobConfigInput) *CronJobConfigUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateCronJobConfigInput on the update-one builder.
func (u *CronJobConfigUpdateOne) SetInput(i UpdateCronJobConfigInput) *CronJobConfigUpdateOne {
	i.Mutate(u.Mutation())
	return u
}

// CreateJobExecutionHistoryInput represents a mutation input for creating jobexecutionhistories.
type CreateJobExecutionHistoryInput struct {
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
	JobName         string
	Status          jobexecutionhistory.Status
	StartedAt       time.Time
	CompletedAt     *time.Time
	DurationSeconds *int
	TotalProcessed  *int
	SuccessfulCount *int
	FailedCount     *int
	APICallsMade    *int
	QuotaRemaining  *int
	ErrorSummary    *string
	ProfileEntryIDs []ulid.ID
}

// Mutate applies the CreateJobExecutionHistoryInput on the JobExecutionHistoryCreate builder.
func (i *CreateJobExecutionHistoryInput) Mutate(m *JobExecutionHistoryCreate) {
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	m.SetJobName(i.JobName)
	m.SetStatus(i.Status)
	m.SetStartedAt(i.StartedAt)
	if v := i.CompletedAt; v != nil {
		m.SetCompletedAt(*v)
	}
	if v := i.DurationSeconds; v != nil {
		m.SetDurationSeconds(*v)
	}
	if v := i.TotalProcessed; v != nil {
		m.SetTotalProcessed(*v)
	}
	if v := i.SuccessfulCount; v != nil {
		m.SetSuccessfulCount(*v)
	}
	if v := i.FailedCount; v != nil {
		m.SetFailedCount(*v)
	}
	if v := i.APICallsMade; v != nil {
		m.SetAPICallsMade(*v)
	}
	if v := i.QuotaRemaining; v != nil {
		m.SetQuotaRemaining(*v)
	}
	if v := i.ErrorSummary; v != nil {
		m.SetErrorSummary(*v)
	}
	if ids := i.ProfileEntryIDs; len(ids) > 0 {
		m.AddProfileEntryIDs(ids...)
	}
}

// SetInput applies the change-set in the CreateJobExecutionHistoryInput on the create builder.
func (c *JobExecutionHistoryCreate) SetInput(i CreateJobExecutionHistoryInput) *JobExecutionHistoryCreate {
	i.Mutate(c)
	return c
}

// UpdateJobExecutionHistoryInput represents a mutation input for updating jobexecutionhistories.
type UpdateJobExecutionHistoryInput struct {
	ID                    ulid.ID
	UpdatedAt             *time.Time
	JobName               *string
	Status                *jobexecutionhistory.Status
	StartedAt             *time.Time
	CompletedAt           *time.Time
	ClearCompletedAt      bool
	DurationSeconds       *int
	TotalProcessed        *int
	SuccessfulCount       *int
	FailedCount           *int
	APICallsMade          *int
	QuotaRemaining        *int
	ErrorSummary          *string
	ClearErrorSummary     bool
	AddProfileEntryIDs    []ulid.ID
	RemoveProfileEntryIDs []ulid.ID
}

// Mutate applies the UpdateJobExecutionHistoryInput on the JobExecutionHistoryMutation.
func (i *UpdateJobExecutionHistoryInput) Mutate(m *JobExecutionHistoryMutation) {
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.JobName; v != nil {
		m.SetJobName(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.StartedAt; v != nil {
		m.SetStartedAt(*v)
	}
	if i.ClearCompletedAt {
		m.ClearCompletedAt()
	}
	if v := i.CompletedAt; v != nil {
		m.SetCompletedAt(*v)
	}
	if v := i.DurationSeconds; v != nil {
		m.SetDurationSeconds(*v)
	}
	if v := i.TotalProcessed; v != nil {
		m.SetTotalProcessed(*v)
	}
	if v := i.SuccessfulCount; v != nil {
		m.SetSuccessfulCount(*v)
	}
	if v := i.FailedCount; v != nil {
		m.SetFailedCount(*v)
	}
	if v := i.APICallsMade; v != nil {
		m.SetAPICallsMade(*v)
	}
	if v := i.QuotaRemaining; v != nil {
		m.SetQuotaRemaining(*v)
	}
	if i.ClearErrorSummary {
		m.ClearErrorSummary()
	}
	if v := i.ErrorSummary; v != nil {
		m.SetErrorSummary(*v)
	}
	if ids := i.AddProfileEntryIDs; len(ids) > 0 {
		m.AddProfileEntryIDs(ids...)
	}
	if ids := i.RemoveProfileEntryIDs; len(ids) > 0 {
		m.RemoveProfileEntryIDs(ids...)
	}
}

// SetInput applies the change-set in the UpdateJobExecutionHistoryInput on the update builder.
func (u *JobExecutionHistoryUpdate) SetInput(i UpdateJobExecutionHistoryInput) *JobExecutionHistoryUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateJobExecutionHistoryInput on the update-one builder.
func (u *JobExecutionHistoryUpdateOne) SetInput(i UpdateJobExecutionHistoryInput) *JobExecutionHistoryUpdateOne {
	i.Mutate(u.Mutation())
	return u
}

// CreateProfileInput represents a mutation input for creating profiles.
type CreateProfileInput struct {
	Urn              string
	Username         *string
	FirstName        *string
	LastName         *string
	Headline         *string
	Title            *string
	Country          *string
	City             *string
	Educations       *[]map[string]interface{}
	Positions        *[]map[string]interface{}
	Skills           *[]map[string]interface{}
	GeoData          *map[string]interface{}
	RawDataS3Key     *string
	CleanedDataS3Key *string
	SourceFile       *string
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	ProfileEntryID   *ulid.ID
}

// Mutate applies the CreateProfileInput on the ProfileCreate builder.
func (i *CreateProfileInput) Mutate(m *ProfileCreate) {
	m.SetUrn(i.Urn)
	if v := i.Username; v != nil {
		m.SetUsername(*v)
	}
	if v := i.FirstName; v != nil {
		m.SetFirstName(*v)
	}
	if v := i.LastName; v != nil {
		m.SetLastName(*v)
	}
	if v := i.Headline; v != nil {
		m.SetHeadline(*v)
	}
	if v := i.Title; v != nil {
		m.SetTitle(*v)
	}
	if v := i.Country; v != nil {
		m.SetCountry(*v)
	}
	if v := i.City; v != nil {
		m.SetCity(*v)
	}
	if v := i.Educations; v != nil {
		m.SetEducations(*v)
	}
	if v := i.Positions; v != nil {
		m.SetPositions(*v)
	}
	if v := i.Skills; v != nil {
		m.SetSkills(*v)
	}
	if v := i.GeoData; v != nil {
		m.SetGeoData(*v)
	}
	if v := i.RawDataS3Key; v != nil {
		m.SetRawDataS3Key(*v)
	}
	if v := i.CleanedDataS3Key; v != nil {
		m.SetCleanedDataS3Key(*v)
	}
	if v := i.SourceFile; v != nil {
		m.SetSourceFile(*v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.ProfileEntryID; v != nil {
		m.SetProfileEntryID(*v)
	}
}

// SetInput applies the change-set in the CreateProfileInput on the create builder.
func (c *ProfileCreate) SetInput(i CreateProfileInput) *ProfileCreate {
	i.Mutate(c)
	return c
}

// UpdateProfileInput represents a mutation input for updating profiles.
type UpdateProfileInput struct {
	ID                    ulid.ID
	Urn                   *string
	Username              *string
	ClearUsername         bool
	FirstName             *string
	ClearFirstName        bool
	LastName              *string
	ClearLastName         bool
	Headline              *string
	ClearHeadline         bool
	Title                 *string
	ClearTitle            bool
	Country               *string
	ClearCountry          bool
	City                  *string
	ClearCity             bool
	Educations            *[]map[string]interface{}
	ClearEducations       bool
	Positions             *[]map[string]interface{}
	ClearPositions        bool
	Skills                *[]map[string]interface{}
	ClearSkills           bool
	GeoData               *map[string]interface{}
	ClearGeoData          bool
	RawDataS3Key          *string
	ClearRawDataS3Key     bool
	CleanedDataS3Key      *string
	ClearCleanedDataS3Key bool
	SourceFile            *string
	ClearSourceFile       bool
	UpdatedAt             *time.Time
	ProfileEntryID        *ulid.ID
	ClearProfileEntry     bool
}

// Mutate applies the UpdateProfileInput on the ProfileMutation.
func (i *UpdateProfileInput) Mutate(m *ProfileMutation) {
	if v := i.Urn; v != nil {
		m.SetUrn(*v)
	}
	if i.ClearUsername {
		m.ClearUsername()
	}
	if v := i.Username; v != nil {
		m.SetUsername(*v)
	}
	if i.ClearFirstName {
		m.ClearFirstName()
	}
	if v := i.FirstName; v != nil {
		m.SetFirstName(*v)
	}
	if i.ClearLastName {
		m.ClearLastName()
	}
	if v := i.LastName; v != nil {
		m.SetLastName(*v)
	}
	if i.ClearHeadline {
		m.ClearHeadline()
	}
	if v := i.Headline; v != nil {
		m.SetHeadline(*v)
	}
	if i.ClearTitle {
		m.ClearTitle()
	}
	if v := i.Title; v != nil {
		m.SetTitle(*v)
	}
	if i.ClearCountry {
		m.ClearCountry()
	}
	if v := i.Country; v != nil {
		m.SetCountry(*v)
	}
	if i.ClearCity {
		m.ClearCity()
	}
	if v := i.City; v != nil {
		m.SetCity(*v)
	}
	if i.ClearEducations {
		m.ClearEducations()
	}
	if v := i.Educations; v != nil {
		m.SetEducations(*v)
	}
	if i.ClearPositions {
		m.ClearPositions()
	}
	if v := i.Positions; v != nil {
		m.SetPositions(*v)
	}
	if i.ClearSkills {
		m.ClearSkills()
	}
	if v := i.Skills; v != nil {
		m.SetSkills(*v)
	}
	if i.ClearGeoData {
		m.ClearGeoData()
	}
	if v := i.GeoData; v != nil {
		m.SetGeoData(*v)
	}
	if i.ClearRawDataS3Key {
		m.ClearRawDataS3Key()
	}
	if v := i.RawDataS3Key; v != nil {
		m.SetRawDataS3Key(*v)
	}
	if i.ClearCleanedDataS3Key {
		m.ClearCleanedDataS3Key()
	}
	if v := i.CleanedDataS3Key; v != nil {
		m.SetCleanedDataS3Key(*v)
	}
	if i.ClearSourceFile {
		m.ClearSourceFile()
	}
	if v := i.SourceFile; v != nil {
		m.SetSourceFile(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if i.ClearProfileEntry {
		m.ClearProfileEntry()
	}
	if v := i.ProfileEntryID; v != nil {
		m.SetProfileEntryID(*v)
	}
}

// SetInput applies the change-set in the UpdateProfileInput on the update builder.
func (u *ProfileUpdate) SetInput(i UpdateProfileInput) *ProfileUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateProfileInput on the update-one builder.
func (u *ProfileUpdateOne) SetInput(i UpdateProfileInput) *ProfileUpdateOne {
	i.Mutate(u.Mutation())
	return u
}

// CreateProfileEntryInput represents a mutation input for creating profileentries.
type CreateProfileEntryInput struct {
	CreatedAt         *time.Time
	UpdatedAt         *time.Time
	LinkedinUrn       string
	Gender            *string
	Status            *profileentry.Status
	ProfileData       *map[string]interface{}
	TemplateJSONS3Key *string
	RawResponseS3Key  *string
	FetchCount        *int
	LastFetchedAt     *time.Time
	ErrorMessage      *string
	ProfileID         *ulid.ID
	JobExecutionIDs   []ulid.ID
}

// Mutate applies the CreateProfileEntryInput on the ProfileEntryCreate builder.
func (i *CreateProfileEntryInput) Mutate(m *ProfileEntryCreate) {
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	m.SetLinkedinUrn(i.LinkedinUrn)
	if v := i.Gender; v != nil {
		m.SetGender(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.ProfileData; v != nil {
		m.SetProfileData(*v)
	}
	if v := i.TemplateJSONS3Key; v != nil {
		m.SetTemplateJSONS3Key(*v)
	}
	if v := i.RawResponseS3Key; v != nil {
		m.SetRawResponseS3Key(*v)
	}
	if v := i.FetchCount; v != nil {
		m.SetFetchCount(*v)
	}
	if v := i.LastFetchedAt; v != nil {
		m.SetLastFetchedAt(*v)
	}
	if v := i.ErrorMessage; v != nil {
		m.SetErrorMessage(*v)
	}
	if v := i.ProfileID; v != nil {
		m.SetProfileID(*v)
	}
	if ids := i.JobExecutionIDs; len(ids) > 0 {
		m.AddJobExecutionIDs(ids...)
	}
}

// SetInput applies the change-set in the CreateProfileEntryInput on the create builder.
func (c *ProfileEntryCreate) SetInput(i CreateProfileEntryInput) *ProfileEntryCreate {
	i.Mutate(c)
	return c
}

// UpdateProfileEntryInput represents a mutation input for updating profileentries.
type UpdateProfileEntryInput struct {
	ID                     ulid.ID
	UpdatedAt              *time.Time
	LinkedinUrn            *string
	Gender                 *string
	ClearGender            bool
	Status                 *profileentry.Status
	ProfileData            *map[string]interface{}
	ClearProfileData       bool
	TemplateJSONS3Key      *string
	ClearTemplateJSONS3Key bool
	RawResponseS3Key       *string
	ClearRawResponseS3Key  bool
	FetchCount             *int
	LastFetchedAt          *time.Time
	ClearLastFetchedAt     bool
	ErrorMessage           *string
	ClearErrorMessage      bool
	ProfileID              *ulid.ID
	ClearProfile           bool
	AddJobExecutionIDs     []ulid.ID
	RemoveJobExecutionIDs  []ulid.ID
}

// Mutate applies the UpdateProfileEntryInput on the ProfileEntryMutation.
func (i *UpdateProfileEntryInput) Mutate(m *ProfileEntryMutation) {
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.LinkedinUrn; v != nil {
		m.SetLinkedinUrn(*v)
	}
	if i.ClearGender {
		m.ClearGender()
	}
	if v := i.Gender; v != nil {
		m.SetGender(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if i.ClearProfileData {
		m.ClearProfileData()
	}
	if v := i.ProfileData; v != nil {
		m.SetProfileData(*v)
	}
	if i.ClearTemplateJSONS3Key {
		m.ClearTemplateJSONS3Key()
	}
	if v := i.TemplateJSONS3Key; v != nil {
		m.SetTemplateJSONS3Key(*v)
	}
	if i.ClearRawResponseS3Key {
		m.ClearRawResponseS3Key()
	}
	if v := i.RawResponseS3Key; v != nil {
		m.SetRawResponseS3Key(*v)
	}
	if v := i.FetchCount; v != nil {
		m.SetFetchCount(*v)
	}
	if i.ClearLastFetchedAt {
		m.ClearLastFetchedAt()
	}
	if v := i.LastFetchedAt; v != nil {
		m.SetLastFetchedAt(*v)
	}
	if i.ClearErrorMessage {
		m.ClearErrorMessage()
	}
	if v := i.ErrorMessage; v != nil {
		m.SetErrorMessage(*v)
	}
	if i.ClearProfile {
		m.ClearProfile()
	}
	if v := i.ProfileID; v != nil {
		m.SetProfileID(*v)
	}
	if ids := i.AddJobExecutionIDs; len(ids) > 0 {
		m.AddJobExecutionIDs(ids...)
	}
	if ids := i.RemoveJobExecutionIDs; len(ids) > 0 {
		m.RemoveJobExecutionIDs(ids...)
	}
}

// SetInput applies the change-set in the UpdateProfileEntryInput on the update builder.
func (u *ProfileEntryUpdate) SetInput(i UpdateProfileEntryInput) *ProfileEntryUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateProfileEntryInput on the update-one builder.
func (u *ProfileEntryUpdateOne) SetInput(i UpdateProfileEntryInput) *ProfileEntryUpdateOne {
	i.Mutate(u.Mutation())
	return u
}

// CreateTodoInput represents a mutation input for creating todos.
type CreateTodoInput struct {
	Name      *string
	Status    *todo.Status
	Priority  *int
	CreatedAt *time.Time
	UpdatedAt *time.Time
	UserID    *ulid.ID
}

// Mutate applies the CreateTodoInput on the TodoCreate builder.
func (i *CreateTodoInput) Mutate(m *TodoCreate) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Priority; v != nil {
		m.SetPriority(*v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.UserID; v != nil {
		m.SetUserID(*v)
	}
}

// SetInput applies the change-set in the CreateTodoInput on the create builder.
func (c *TodoCreate) SetInput(i CreateTodoInput) *TodoCreate {
	i.Mutate(c)
	return c
}

// UpdateTodoInput represents a mutation input for updating todos.
type UpdateTodoInput struct {
	ID        ulid.ID
	Name      *string
	Status    *todo.Status
	Priority  *int
	UpdatedAt *time.Time
	UserID    *ulid.ID
	ClearUser bool
}

// Mutate applies the UpdateTodoInput on the TodoMutation.
func (i *UpdateTodoInput) Mutate(m *TodoMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Priority; v != nil {
		m.SetPriority(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if i.ClearUser {
		m.ClearUser()
	}
	if v := i.UserID; v != nil {
		m.SetUserID(*v)
	}
}

// SetInput applies the change-set in the UpdateTodoInput on the update builder.
func (u *TodoUpdate) SetInput(i UpdateTodoInput) *TodoUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateTodoInput on the update-one builder.
func (u *TodoUpdateOne) SetInput(i UpdateTodoInput) *TodoUpdateOne {
	i.Mutate(u.Mutation())
	return u
}

// CreateUserInput represents a mutation input for creating users.
type CreateUserInput struct {
	Name      string
	Age       int
	Email     string
	Password  string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	TodoIDs   []ulid.ID
}

// Mutate applies the CreateUserInput on the UserCreate builder.
func (i *CreateUserInput) Mutate(m *UserCreate) {
	m.SetName(i.Name)
	m.SetAge(i.Age)
	m.SetEmail(i.Email)
	m.SetPassword(i.Password)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if ids := i.TodoIDs; len(ids) > 0 {
		m.AddTodoIDs(ids...)
	}
}

// SetInput applies the change-set in the CreateUserInput on the create builder.
func (c *UserCreate) SetInput(i CreateUserInput) *UserCreate {
	i.Mutate(c)
	return c
}

// UpdateUserInput represents a mutation input for updating users.
type UpdateUserInput struct {
	ID            ulid.ID
	Name          *string
	Age           *int
	Email         *string
	Password      *string
	UpdatedAt     *time.Time
	AddTodoIDs    []ulid.ID
	RemoveTodoIDs []ulid.ID
}

// Mutate applies the UpdateUserInput on the UserMutation.
func (i *UpdateUserInput) Mutate(m *UserMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Age; v != nil {
		m.SetAge(*v)
	}
	if v := i.Email; v != nil {
		m.SetEmail(*v)
	}
	if v := i.Password; v != nil {
		m.SetPassword(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if ids := i.AddTodoIDs; len(ids) > 0 {
		m.AddTodoIDs(ids...)
	}
	if ids := i.RemoveTodoIDs; len(ids) > 0 {
		m.RemoveTodoIDs(ids...)
	}
}

// SetInput applies the change-set in the UpdateUserInput on the update builder.
func (u *UserUpdate) SetInput(i UpdateUserInput) *UserUpdate {
	i.Mutate(u.Mutation())
	return u
}

// SetInput applies the change-set in the UpdateUserInput on the update-one builder.
func (u *UserUpdateOne) SetInput(i UpdateUserInput) *UserUpdateOne {
	i.Mutate(u.Mutation())
	return u
}
