// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sheng-go-backend/ent/profilepost"
	"sheng-go-backend/ent/schema/ulid"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ProfilePost is the model entity for the ProfilePost schema.
type ProfilePost struct {
	config `json:"-"`
	// ID of the ent.
	ID ulid.ID `json:"id,omitempty"`
	// LinkedIn username extracted from profile_url
	ProfileUsername string `json:"profile_username,omitempty"`
	// Fetch status for this profile's posts
	FetchStatus profilepost.FetchStatus `json:"fetch_status,omitempty"`
	// S3 key for the raw posts JSON file
	S3Key *string `json:"s3_key,omitempty"`
	// Error message if fetch failed
	ErrorMessage *string `json:"error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProfilePostQuery when eager-loading is set.
	Edges        ProfilePostEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProfilePostEdges holds the relations/edges for other nodes in the graph.
type ProfilePostEdges struct {
	// Individual post items fetched for this profile
	Items []*ProfilePostItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedItems map[string][]*ProfilePostItem
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e ProfilePostEdges) ItemsOrErr() ([]*ProfilePostItem, error) {
	if e.loadedTypes[0] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProfilePost) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case profilepost.FieldProfileUsername, profilepost.FieldFetchStatus, profilepost.FieldS3Key, profilepost.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case profilepost.FieldCreatedAt, profilepost.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case profilepost.FieldID:
			values[i] = new(ulid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProfilePost fields.
func (pp *ProfilePost) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case profilepost.FieldID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pp.ID = *value
			}
		case profilepost.FieldProfileUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_username", values[i])
			} else if value.Valid {
				pp.ProfileUsername = value.String
			}
		case profilepost.FieldFetchStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fetch_status", values[i])
			} else if value.Valid {
				pp.FetchStatus = profilepost.FetchStatus(value.String)
			}
		case profilepost.FieldS3Key:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field s3_key", values[i])
			} else if value.Valid {
				pp.S3Key = new(string)
				*pp.S3Key = value.String
			}
		case profilepost.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				pp.ErrorMessage = new(string)
				*pp.ErrorMessage = value.String
			}
		case profilepost.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pp.CreatedAt = value.Time
			}
		case profilepost.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pp.UpdatedAt = value.Time
			}
		default:
			pp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProfilePost.
// This includes values selected through modifiers, order, etc.
func (pp *ProfilePost) Value(name string) (ent.Value, error) {
	return pp.selectValues.Get(name)
}

// QueryItems queries the "items" edge of the ProfilePost entity.
func (pp *ProfilePost) QueryItems() *ProfilePostItemQuery {
	return NewProfilePostClient(pp.config).QueryItems(pp)
}

// Update returns a builder for updating this ProfilePost.
// Note that you need to call ProfilePost.Unwrap() before calling this method if this ProfilePost
// was returned from a transaction, and the transaction was committed or rolled back.
func (pp *ProfilePost) Update() *ProfilePostUpdateOne {
	return NewProfilePostClient(pp.config).UpdateOne(pp)
}

// Unwrap unwraps the ProfilePost entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pp *ProfilePost) Unwrap() *ProfilePost {
	_tx, ok := pp.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProfilePost is not a transactional entity")
	}
	pp.config.driver = _tx.drv
	return pp
}

// String implements the fmt.Stringer.
func (pp *ProfilePost) String() string {
	var builder strings.Builder
	builder.WriteString("ProfilePost(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pp.ID))
	builder.WriteString("profile_username=")
	builder.WriteString(pp.ProfileUsername)
	builder.WriteString(", ")
	builder.WriteString("fetch_status=")
	builder.WriteString(fmt.Sprintf("%v", pp.FetchStatus))
	builder.WriteString(", ")
	if v := pp.S3Key; v != nil {
		builder.WriteString("s3_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := pp.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pp.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pp.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NamedItems returns the Items named value or an error if the edge was not
// loaded in eager-loading with this name.
func (pp *ProfilePost) NamedItems(name string) ([]*ProfilePostItem, error) {
	if pp.Edges.namedItems == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := pp.Edges.namedItems[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (pp *ProfilePost) appendNamedItems(name string, edges ...*ProfilePostItem) {
	if pp.Edges.namedItems == nil {
		pp.Edges.namedItems = make(map[string][]*ProfilePostItem)
	}
	if len(edges) == 0 {
		pp.Edges.namedItems[name] = []*ProfilePostItem{}
	} else {
		pp.Edges.namedItems[name] = append(pp.Edges.namedItems[name], edges...)
	}
}

// ProfilePosts is a parsable slice of ProfilePost.
type ProfilePosts []*ProfilePost
