// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sheng-go-backend/ent/profilepost"
	"sheng-go-backend/ent/profilepostitem"
	"sheng-go-backend/ent/schema/ulid"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfilePostCreate is the builder for creating a ProfilePost entity.
type ProfilePostCreate struct {
	config
	mutation *ProfilePostMutation
	hooks    []Hook
}

// SetProfileUsername sets the "profile_username" field.
func (ppc *ProfilePostCreate) SetProfileUsername(s string) *ProfilePostCreate {
	ppc.mutation.SetProfileUsername(s)
	return ppc
}

// SetFetchStatus sets the "fetch_status" field.
func (ppc *ProfilePostCreate) SetFetchStatus(ps profilepost.FetchStatus) *ProfilePostCreate {
	ppc.mutation.SetFetchStatus(ps)
	return ppc
}

// SetNillableFetchStatus sets the "fetch_status" field if the given value is not nil.
func (ppc *ProfilePostCreate) SetNillableFetchStatus(ps *profilepost.FetchStatus) *ProfilePostCreate {
	if ps != nil {
		ppc.SetFetchStatus(*ps)
	}
	return ppc
}

// SetS3Key sets the "s3_key" field.
func (ppc *ProfilePostCreate) SetS3Key(s string) *ProfilePostCreate {
	ppc.mutation.SetS3Key(s)
	return ppc
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (ppc *ProfilePostCreate) SetNillableS3Key(s *string) *ProfilePostCreate {
	if s != nil {
		ppc.SetS3Key(*s)
	}
	return ppc
}

// SetErrorMessage sets the "error_message" field.
func (ppc *ProfilePostCreate) SetErrorMessage(s string) *ProfilePostCreate {
	ppc.mutation.SetErrorMessage(s)
	return ppc
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (ppc *ProfilePostCreate) SetNillableErrorMessage(s *string) *ProfilePostCreate {
	if s != nil {
		ppc.SetErrorMessage(*s)
	}
	return ppc
}

// SetCreatedAt sets the "created_at" field.
func (ppc *ProfilePostCreate) SetCreatedAt(t time.Time) *ProfilePostCreate {
	ppc.mutation.SetCreatedAt(t)
	return ppc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ppc *ProfilePostCreate) SetNillableCreatedAt(t *time.Time) *ProfilePostCreate {
	if t != nil {
		ppc.SetCreatedAt(*t)
	}
	return ppc
}

// SetUpdatedAt sets the "updated_at" field.
func (ppc *ProfilePostCreate) SetUpdatedAt(t time.Time) *ProfilePostCreate {
	ppc.mutation.SetUpdatedAt(t)
	return ppc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ppc *ProfilePostCreate) SetNillableUpdatedAt(t *time.Time) *ProfilePostCreate {
	if t != nil {
		ppc.SetUpdatedAt(*t)
	}
	return ppc
}

// SetID sets the "id" field.
func (ppc *ProfilePostCreate) SetID(u ulid.ID) *ProfilePostCreate {
	ppc.mutation.SetID(u)
	return ppc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ppc *ProfilePostCreate) SetNillableID(u *ulid.ID) *ProfilePostCreate {
	if u != nil {
		ppc.SetID(*u)
	}
	return ppc
}

// AddItemIDs adds the "items" edge to the ProfilePostItem entity by IDs.
func (ppc *ProfilePostCreate) AddItemIDs(ids ...ulid.ID) *ProfilePostCreate {
	ppc.mutation.AddItemIDs(ids...)
	return ppc
}

// AddItems adds the "items" edges to the ProfilePostItem entity.
func (ppc *ProfilePostCreate) AddItems(p ...*ProfilePostItem) *ProfilePostCreate {
	ids := make([]ulid.ID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ppc.AddItemIDs(ids...)
}

// Mutation returns the ProfilePostMutation object of the builder.
func (ppc *ProfilePostCreate) Mutation() *ProfilePostMutation {
	return ppc.mutation
}

// Save creates the ProfilePost in the database.
func (ppc *ProfilePostCreate) Save(ctx context.Context) (*ProfilePost, error) {
	ppc.defaults()
	return withHooks(ctx, ppc.sqlSave, ppc.mutation, ppc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ppc *ProfilePostCreate) SaveX(ctx context.Context) *ProfilePost {
	v, err := ppc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ppc *ProfilePostCreate) Exec(ctx context.Context) error {
	_, err := ppc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppc *ProfilePostCreate) ExecX(ctx context.Context) {
	if err := ppc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ppc *ProfilePostCreate) defaults() {
	if _, ok := ppc.mutation.FetchStatus(); !ok {
		v := profilepost.DefaultFetchStatus
		ppc.mutation.SetFetchStatus(v)
	}
	if _, ok := ppc.mutation.CreatedAt(); !ok {
		v := profilepost.DefaultCreatedAt()
		ppc.mutation.SetCreatedAt(v)
	}
	if _, ok := ppc.mutation.UpdatedAt(); !ok {
		v := profilepost.DefaultUpdatedAt()
		ppc.mutation.SetUpdatedAt(v)
	}
	if _, ok := ppc.mutation.ID(); !ok {
		v := profilepost.DefaultID()
		ppc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ppc *ProfilePostCreate) check() error {
	if _, ok := ppc.mutation.ProfileUsername(); !ok {
		return &ValidationError{Name: "profile_username", err: errors.New(`ent: missing required field "ProfilePost.profile_username"`)}
	}
	if v, ok := ppc.mutation.ProfileUsername(); ok {
		if err := profilepost.ProfileUsernameValidator(v); err != nil {
			return &ValidationError{Name: "profile_username", err: fmt.Errorf(`ent: validator failed for field "ProfilePost.profile_username": %w`, err)}
		}
	}
	if _, ok := ppc.mutation.FetchStatus(); !ok {
		return &ValidationError{Name: "fetch_status", err: errors.New(`ent: missing required field "ProfilePost.fetch_status"`)}
	}
	if v, ok := ppc.mutation.FetchStatus(); ok {
		if err := profilepost.FetchStatusValidator(v); err != nil {
			return &ValidationError{Name: "fetch_status", err: fmt.Errorf(`ent: validator failed for field "ProfilePost.fetch_status": %w`, err)}
		}
	}
	if v, ok := ppc.mutation.S3Key(); ok {
		if err := profilepost.S3KeyValidator(v); err != nil {
			return &ValidationError{Name: "s3_key", err: fmt.Errorf(`ent: validator failed for field "ProfilePost.s3_key": %w`, err)}
		}
	}
	if _, ok := ppc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProfilePost.created_at"`)}
	}
	if _, ok := ppc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProfilePost.updated_at"`)}
	}
	return nil
}

func (ppc *ProfilePostCreate) sqlSave(ctx context.Context) (*ProfilePost, error) {
	if err := ppc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ppc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ppc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ppc.mutation.id = &_node.ID
	ppc.mutation.done = true
	return _node, nil
}

func (ppc *ProfilePostCreate) createSpec() (*ProfilePost, *sqlgraph.CreateSpec) {
	var (
		_node = &ProfilePost{config: ppc.config}
		_spec = sqlgraph.NewCreateSpec(profilepost.Table, sqlgraph.NewFieldSpec(profilepost.FieldID, field.TypeString))
	)
	if id, ok := ppc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ppc.mutation.ProfileUsername(); ok {
		_spec.SetField(profilepost.FieldProfileUsername, field.TypeString, value)
		_node.ProfileUsername = value
	}
	if value, ok := ppc.mutation.FetchStatus(); ok {
		_spec.SetField(profilepost.FieldFetchStatus, field.TypeEnum, value)
		_node.FetchStatus = value
	}
	if value, ok := ppc.mutation.S3Key(); ok {
		_spec.SetField(profilepost.FieldS3Key, field.TypeString, value)
		_node.S3Key = &value
	}
	if value, ok := ppc.mutation.ErrorMessage(); ok {
		_spec.SetField(profilepost.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := ppc.mutation.CreatedAt(); ok {
		_spec.SetField(profilepost.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ppc.mutation.UpdatedAt(); ok {
		_spec.SetField(profilepost.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := ppc.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profilepost.ItemsTable,
			Columns: []string{profilepost.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profilepostitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProfilePostCreateBulk is the builder for creating many ProfilePost entities in bulk.
type ProfilePostCreateBulk struct {
	config
	err      error
	builders []*ProfilePostCreate
}

// Save creates the ProfilePost entities in the database.
func (ppcb *ProfilePostCreateBulk) Save(ctx context.Context) ([]*ProfilePost, error) {
	if ppcb.err != nil {
		return nil, ppcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ppcb.builders))
	nodes := make([]*ProfilePost, len(ppcb.builders))
	mutators := make([]Mutator, len(ppcb.builders))
	for i := range ppcb.builders {
		func(i int, root context.Context) {
			builder := ppcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProfilePostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ppcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ppcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ppcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ppcb *ProfilePostCreateBulk) SaveX(ctx context.Context) []*ProfilePost {
	v, err := ppcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ppcb *ProfilePostCreateBulk) Exec(ctx context.Context) error {
	_, err := ppcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppcb *ProfilePostCreateBulk) ExecX(ctx context.Context) {
	if err := ppcb.Exec(ctx); err != nil {
		panic(err)
	}
}
