// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"sheng-go-backend/ent/profilepost"
	"sheng-go-backend/ent/profilepostitem"
	"sheng-go-backend/ent/schema/ulid"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ProfilePostItem is the model entity for the ProfilePostItem schema.
type ProfilePostItem struct {
	config `json:"-"`
	// ID of the ent.
	ID ulid.ID `json:"id,omitempty"`
	// LinkedIn username this post belongs to
	ProfileUsername string `json:"profile_username,omitempty"`
	// LinkedIn post URN (numeric ID string from API)
	PostUrn *string `json:"post_urn,omitempty"`
	// postUrl from API response
	PostURL *string `json:"post_url,omitempty"`
	// Post body text
	Text *string `json:"text,omitempty"`
	// contentType: post, image, article, linkedInVideo, etc.
	ContentType *string `json:"content_type,omitempty"`
	// Whether this is a reshared post
	IsRepost bool `json:"is_repost,omitempty"`
	// totalReactionCount from API
	TotalReactions int `json:"total_reactions,omitempty"`
	// likeCount from API
	LikeCount int `json:"like_count,omitempty"`
	// commentsCount from API
	CommentsCount int `json:"comments_count,omitempty"`
	// repostsCount from API
	RepostsCount int `json:"reposts_count,omitempty"`
	// empathyCount (care reactions) from API
	EmpathyCount int `json:"empathy_count,omitempty"`
	// praiseCount (celebrate reactions) from API
	PraiseCount int `json:"praise_count,omitempty"`
	// funnyCount reactions from API
	FunnyCount int `json:"funny_count,omitempty"`
	// InterestCount (insightful reactions) from API
	InterestCount int `json:"interest_count,omitempty"`
	// Parsed from postedDateTimestamp (ms unix)
	PostedAt *time.Time `json:"posted_at,omitempty"`
	// Full raw post object from RapidAPI
	RawData map[string]interface{} `json:"raw_data,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProfilePostItemQuery when eager-loading is set.
	Edges              ProfilePostItemEdges `json:"edges"`
	profile_post_items *ulid.ID
	selectValues       sql.SelectValues
}

// ProfilePostItemEdges holds the relations/edges for other nodes in the graph.
type ProfilePostItemEdges struct {
	// Parent ProfilePost record
	ProfilePost *ProfilePost `json:"profile_post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// ProfilePostOrErr returns the ProfilePost value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProfilePostItemEdges) ProfilePostOrErr() (*ProfilePost, error) {
	if e.ProfilePost != nil {
		return e.ProfilePost, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: profilepost.Label}
	}
	return nil, &NotLoadedError{edge: "profile_post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProfilePostItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case profilepostitem.FieldRawData:
			values[i] = new([]byte)
		case profilepostitem.FieldIsRepost:
			values[i] = new(sql.NullBool)
		case profilepostitem.FieldTotalReactions, profilepostitem.FieldLikeCount, profilepostitem.FieldCommentsCount, profilepostitem.FieldRepostsCount, profilepostitem.FieldEmpathyCount, profilepostitem.FieldPraiseCount, profilepostitem.FieldFunnyCount, profilepostitem.FieldInterestCount:
			values[i] = new(sql.NullInt64)
		case profilepostitem.FieldProfileUsername, profilepostitem.FieldPostUrn, profilepostitem.FieldPostURL, profilepostitem.FieldText, profilepostitem.FieldContentType:
			values[i] = new(sql.NullString)
		case profilepostitem.FieldPostedAt, profilepostitem.FieldCreatedAt, profilepostitem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case profilepostitem.FieldID:
			values[i] = new(ulid.ID)
		case profilepostitem.ForeignKeys[0]: // profile_post_items
			values[i] = &sql.NullScanner{S: new(ulid.ID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProfilePostItem fields.
func (ppi *ProfilePostItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case profilepostitem.FieldID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ppi.ID = *value
			}
		case profilepostitem.FieldProfileUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_username", values[i])
			} else if value.Valid {
				ppi.ProfileUsername = value.String
			}
		case profilepostitem.FieldPostUrn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field post_urn", values[i])
			} else if value.Valid {
				ppi.PostUrn = new(string)
				*ppi.PostUrn = value.String
			}
		case profilepostitem.FieldPostURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field post_url", values[i])
			} else if value.Valid {
				ppi.PostURL = new(string)
				*ppi.PostURL = value.String
			}
		case profilepostitem.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				ppi.Text = new(string)
				*ppi.Text = value.String
			}
		case profilepostitem.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				ppi.ContentType = new(string)
				*ppi.ContentType = value.String
			}
		case profilepostitem.FieldIsRepost:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_repost", values[i])
			} else if value.Valid {
				ppi.IsRepost = value.Bool
			}
		case profilepostitem.FieldTotalReactions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_reactions", values[i])
			} else if value.Valid {
				ppi.TotalReactions = int(value.Int64)
			}
		case profilepostitem.FieldLikeCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field like_count", values[i])
			} else if value.Valid {
				ppi.LikeCount = int(value.Int64)
			}
		case profilepostitem.FieldCommentsCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field comments_count", values[i])
			} else if value.Valid {
				ppi.CommentsCount = int(value.Int64)
			}
		case profilepostitem.FieldRepostsCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reposts_count", values[i])
			} else if value.Valid {
				ppi.RepostsCount = int(value.Int64)
			}
		case profilepostitem.FieldEmpathyCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field empathy_count", values[i])
			} else if value.Valid {
				ppi.EmpathyCount = int(value.Int64)
			}
		case profilepostitem.FieldPraiseCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field praise_count", values[i])
			} else if value.Valid {
				ppi.PraiseCount = int(value.Int64)
			}
		case profilepostitem.FieldFunnyCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field funny_count", values[i])
			} else if value.Valid {
				ppi.FunnyCount = int(value.Int64)
			}
		case profilepostitem.FieldInterestCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interest_count", values[i])
			} else if value.Valid {
				ppi.InterestCount = int(value.Int64)
			}
		case profilepostitem.FieldPostedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field posted_at", values[i])
			} else if value.Valid {
				ppi.PostedAt = new(time.Time)
				*ppi.PostedAt = value.Time
			}
		case profilepostitem.FieldRawData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field raw_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ppi.RawData); err != nil {
					return fmt.Errorf("unmarshal field raw_data: %w", err)
				}
			}
		case profilepostitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ppi.CreatedAt = value.Time
			}
		case profilepostitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ppi.UpdatedAt = value.Time
			}
		case profilepostitem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field profile_post_items", values[i])
			} else if value.Valid {
				ppi.profile_post_items = new(ulid.ID)
				*ppi.profile_post_items = *value.S.(*ulid.ID)
			}
		default:
			ppi.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProfilePostItem.
// This includes values selected through modifiers, order, etc.
func (ppi *ProfilePostItem) Value(name string) (ent.Value, error) {
	return ppi.selectValues.Get(name)
}

// QueryProfilePost queries the "profile_post" edge of the ProfilePostItem entity.
func (ppi *ProfilePostItem) QueryProfilePost() *ProfilePostQuery {
	return NewProfilePostItemClient(ppi.config).QueryProfilePost(ppi)
}

// Update returns a builder for updating this ProfilePostItem.
// Note that you need to call ProfilePostItem.Unwrap() before calling this method if this ProfilePostItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (ppi *ProfilePostItem) Update() *ProfilePostItemUpdateOne {
	return NewProfilePostItemClient(ppi.config).UpdateOne(ppi)
}

// Unwrap unwraps the ProfilePostItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ppi *ProfilePostItem) Unwrap() *ProfilePostItem {
	_tx, ok := ppi.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProfilePostItem is not a transactional entity")
	}
	ppi.config.driver = _tx.drv
	return ppi
}

// String implements the fmt.Stringer.
func (ppi *ProfilePostItem) String() string {
	var builder strings.Builder
	builder.WriteString("ProfilePostItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ppi.ID))
	builder.WriteString("profile_username=")
	builder.WriteString(ppi.ProfileUsername)
	builder.WriteString(", ")
	if v := ppi.PostUrn; v != nil {
		builder.WriteString("post_urn=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ppi.PostURL; v != nil {
		builder.WriteString("post_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ppi.Text; v != nil {
		builder.WriteString("text=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ppi.ContentType; v != nil {
		builder.WriteString("content_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_repost=")
	builder.WriteString(fmt.Sprintf("%v", ppi.IsRepost))
	builder.WriteString(", ")
	builder.WriteString("total_reactions=")
	builder.WriteString(fmt.Sprintf("%v", ppi.TotalReactions))
	builder.WriteString(", ")
	builder.WriteString("like_count=")
	builder.WriteString(fmt.Sprintf("%v", ppi.LikeCount))
	builder.WriteString(", ")
	builder.WriteString("comments_count=")
	builder.WriteString(fmt.Sprintf("%v", ppi.CommentsCount))
	builder.WriteString(", ")
	builder.WriteString("reposts_count=")
	builder.WriteString(fmt.Sprintf("%v", ppi.RepostsCount))
	builder.WriteString(", ")
	builder.WriteString("empathy_count=")
	builder.WriteString(fmt.Sprintf("%v", ppi.EmpathyCount))
	builder.WriteString(", ")
	builder.WriteString("praise_count=")
	builder.WriteString(fmt.Sprintf("%v", ppi.PraiseCount))
	builder.WriteString(", ")
	builder.WriteString("funny_count=")
	builder.WriteString(fmt.Sprintf("%v", ppi.FunnyCount))
	builder.WriteString(", ")
	builder.WriteString("interest_count=")
	builder.WriteString(fmt.Sprintf("%v", ppi.InterestCount))
	builder.WriteString(", ")
	if v := ppi.PostedAt; v != nil {
		builder.WriteString("posted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("raw_data=")
	builder.WriteString(fmt.Sprintf("%v", ppi.RawData))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ppi.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ppi.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProfilePostItems is a parsable slice of ProfilePostItem.
type ProfilePostItems []*ProfilePostItem
