// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"sheng-go-backend/ent/jobexecutionhistory"
	"sheng-go-backend/ent/predicate"
	"sheng-go-backend/ent/profile"
	"sheng-go-backend/ent/profileentry"
	"sheng-go-backend/ent/schema/ulid"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileEntryQuery is the builder for querying ProfileEntry entities.
type ProfileEntryQuery struct {
	config
	ctx                    *QueryContext
	order                  []profileentry.OrderOption
	inters                 []Interceptor
	predicates             []predicate.ProfileEntry
	withProfile            *ProfileQuery
	withJobExecutions      *JobExecutionHistoryQuery
	modifiers              []func(*sql.Selector)
	loadTotal              []func(context.Context, []*ProfileEntry) error
	withNamedJobExecutions map[string]*JobExecutionHistoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProfileEntryQuery builder.
func (peq *ProfileEntryQuery) Where(ps ...predicate.ProfileEntry) *ProfileEntryQuery {
	peq.predicates = append(peq.predicates, ps...)
	return peq
}

// Limit the number of records to be returned by this query.
func (peq *ProfileEntryQuery) Limit(limit int) *ProfileEntryQuery {
	peq.ctx.Limit = &limit
	return peq
}

// Offset to start from.
func (peq *ProfileEntryQuery) Offset(offset int) *ProfileEntryQuery {
	peq.ctx.Offset = &offset
	return peq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (peq *ProfileEntryQuery) Unique(unique bool) *ProfileEntryQuery {
	peq.ctx.Unique = &unique
	return peq
}

// Order specifies how the records should be ordered.
func (peq *ProfileEntryQuery) Order(o ...profileentry.OrderOption) *ProfileEntryQuery {
	peq.order = append(peq.order, o...)
	return peq
}

// QueryProfile chains the current query on the "profile" edge.
func (peq *ProfileEntryQuery) QueryProfile() *ProfileQuery {
	query := (&ProfileClient{config: peq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := peq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := peq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(profileentry.Table, profileentry.FieldID, selector),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, profileentry.ProfileTable, profileentry.ProfileColumn),
		)
		fromU = sqlgraph.SetNeighbors(peq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJobExecutions chains the current query on the "job_executions" edge.
func (peq *ProfileEntryQuery) QueryJobExecutions() *JobExecutionHistoryQuery {
	query := (&JobExecutionHistoryClient{config: peq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := peq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := peq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(profileentry.Table, profileentry.FieldID, selector),
			sqlgraph.To(jobexecutionhistory.Table, jobexecutionhistory.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, profileentry.JobExecutionsTable, profileentry.JobExecutionsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(peq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProfileEntry entity from the query.
// Returns a *NotFoundError when no ProfileEntry was found.
func (peq *ProfileEntryQuery) First(ctx context.Context) (*ProfileEntry, error) {
	nodes, err := peq.Limit(1).All(setContextOp(ctx, peq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{profileentry.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (peq *ProfileEntryQuery) FirstX(ctx context.Context) *ProfileEntry {
	node, err := peq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProfileEntry ID from the query.
// Returns a *NotFoundError when no ProfileEntry ID was found.
func (peq *ProfileEntryQuery) FirstID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = peq.Limit(1).IDs(setContextOp(ctx, peq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{profileentry.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (peq *ProfileEntryQuery) FirstIDX(ctx context.Context) ulid.ID {
	id, err := peq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProfileEntry entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProfileEntry entity is found.
// Returns a *NotFoundError when no ProfileEntry entities are found.
func (peq *ProfileEntryQuery) Only(ctx context.Context) (*ProfileEntry, error) {
	nodes, err := peq.Limit(2).All(setContextOp(ctx, peq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{profileentry.Label}
	default:
		return nil, &NotSingularError{profileentry.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (peq *ProfileEntryQuery) OnlyX(ctx context.Context) *ProfileEntry {
	node, err := peq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProfileEntry ID in the query.
// Returns a *NotSingularError when more than one ProfileEntry ID is found.
// Returns a *NotFoundError when no entities are found.
func (peq *ProfileEntryQuery) OnlyID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = peq.Limit(2).IDs(setContextOp(ctx, peq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{profileentry.Label}
	default:
		err = &NotSingularError{profileentry.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (peq *ProfileEntryQuery) OnlyIDX(ctx context.Context) ulid.ID {
	id, err := peq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProfileEntries.
func (peq *ProfileEntryQuery) All(ctx context.Context) ([]*ProfileEntry, error) {
	ctx = setContextOp(ctx, peq.ctx, ent.OpQueryAll)
	if err := peq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProfileEntry, *ProfileEntryQuery]()
	return withInterceptors[[]*ProfileEntry](ctx, peq, qr, peq.inters)
}

// AllX is like All, but panics if an error occurs.
func (peq *ProfileEntryQuery) AllX(ctx context.Context) []*ProfileEntry {
	nodes, err := peq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProfileEntry IDs.
func (peq *ProfileEntryQuery) IDs(ctx context.Context) (ids []ulid.ID, err error) {
	if peq.ctx.Unique == nil && peq.path != nil {
		peq.Unique(true)
	}
	ctx = setContextOp(ctx, peq.ctx, ent.OpQueryIDs)
	if err = peq.Select(profileentry.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (peq *ProfileEntryQuery) IDsX(ctx context.Context) []ulid.ID {
	ids, err := peq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (peq *ProfileEntryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, peq.ctx, ent.OpQueryCount)
	if err := peq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, peq, querierCount[*ProfileEntryQuery](), peq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (peq *ProfileEntryQuery) CountX(ctx context.Context) int {
	count, err := peq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (peq *ProfileEntryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, peq.ctx, ent.OpQueryExist)
	switch _, err := peq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (peq *ProfileEntryQuery) ExistX(ctx context.Context) bool {
	exist, err := peq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProfileEntryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (peq *ProfileEntryQuery) Clone() *ProfileEntryQuery {
	if peq == nil {
		return nil
	}
	return &ProfileEntryQuery{
		config:            peq.config,
		ctx:               peq.ctx.Clone(),
		order:             append([]profileentry.OrderOption{}, peq.order...),
		inters:            append([]Interceptor{}, peq.inters...),
		predicates:        append([]predicate.ProfileEntry{}, peq.predicates...),
		withProfile:       peq.withProfile.Clone(),
		withJobExecutions: peq.withJobExecutions.Clone(),
		// clone intermediate query.
		sql:  peq.sql.Clone(),
		path: peq.path,
	}
}

// WithProfile tells the query-builder to eager-load the nodes that are connected to
// the "profile" edge. The optional arguments are used to configure the query builder of the edge.
func (peq *ProfileEntryQuery) WithProfile(opts ...func(*ProfileQuery)) *ProfileEntryQuery {
	query := (&ProfileClient{config: peq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	peq.withProfile = query
	return peq
}

// WithJobExecutions tells the query-builder to eager-load the nodes that are connected to
// the "job_executions" edge. The optional arguments are used to configure the query builder of the edge.
func (peq *ProfileEntryQuery) WithJobExecutions(opts ...func(*JobExecutionHistoryQuery)) *ProfileEntryQuery {
	query := (&JobExecutionHistoryClient{config: peq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	peq.withJobExecutions = query
	return peq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProfileEntry.Query().
//		GroupBy(profileentry.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (peq *ProfileEntryQuery) GroupBy(field string, fields ...string) *ProfileEntryGroupBy {
	peq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProfileEntryGroupBy{build: peq}
	grbuild.flds = &peq.ctx.Fields
	grbuild.label = profileentry.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ProfileEntry.Query().
//		Select(profileentry.FieldCreatedAt).
//		Scan(ctx, &v)
func (peq *ProfileEntryQuery) Select(fields ...string) *ProfileEntrySelect {
	peq.ctx.Fields = append(peq.ctx.Fields, fields...)
	sbuild := &ProfileEntrySelect{ProfileEntryQuery: peq}
	sbuild.label = profileentry.Label
	sbuild.flds, sbuild.scan = &peq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProfileEntrySelect configured with the given aggregations.
func (peq *ProfileEntryQuery) Aggregate(fns ...AggregateFunc) *ProfileEntrySelect {
	return peq.Select().Aggregate(fns...)
}

func (peq *ProfileEntryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range peq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, peq); err != nil {
				return err
			}
		}
	}
	for _, f := range peq.ctx.Fields {
		if !profileentry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if peq.path != nil {
		prev, err := peq.path(ctx)
		if err != nil {
			return err
		}
		peq.sql = prev
	}
	return nil
}

func (peq *ProfileEntryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProfileEntry, error) {
	var (
		nodes       = []*ProfileEntry{}
		_spec       = peq.querySpec()
		loadedTypes = [2]bool{
			peq.withProfile != nil,
			peq.withJobExecutions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProfileEntry).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProfileEntry{config: peq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(peq.modifiers) > 0 {
		_spec.Modifiers = peq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, peq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := peq.withProfile; query != nil {
		if err := peq.loadProfile(ctx, query, nodes, nil,
			func(n *ProfileEntry, e *Profile) { n.Edges.Profile = e }); err != nil {
			return nil, err
		}
	}
	if query := peq.withJobExecutions; query != nil {
		if err := peq.loadJobExecutions(ctx, query, nodes,
			func(n *ProfileEntry) { n.Edges.JobExecutions = []*JobExecutionHistory{} },
			func(n *ProfileEntry, e *JobExecutionHistory) {
				n.Edges.JobExecutions = append(n.Edges.JobExecutions, e)
			}); err != nil {
			return nil, err
		}
	}
	for name, query := range peq.withNamedJobExecutions {
		if err := peq.loadJobExecutions(ctx, query, nodes,
			func(n *ProfileEntry) { n.appendNamedJobExecutions(name) },
			func(n *ProfileEntry, e *JobExecutionHistory) { n.appendNamedJobExecutions(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range peq.loadTotal {
		if err := peq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (peq *ProfileEntryQuery) loadProfile(ctx context.Context, query *ProfileQuery, nodes []*ProfileEntry, init func(*ProfileEntry), assign func(*ProfileEntry, *Profile)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[ulid.ID]*ProfileEntry)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Profile(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(profileentry.ProfileColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.profile_entry_profile
		if fk == nil {
			return fmt.Errorf(`foreign-key "profile_entry_profile" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "profile_entry_profile" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (peq *ProfileEntryQuery) loadJobExecutions(ctx context.Context, query *JobExecutionHistoryQuery, nodes []*ProfileEntry, init func(*ProfileEntry), assign func(*ProfileEntry, *JobExecutionHistory)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[ulid.ID]*ProfileEntry)
	nids := make(map[ulid.ID]map[*ProfileEntry]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(profileentry.JobExecutionsTable)
		s.Join(joinT).On(s.C(jobexecutionhistory.FieldID), joinT.C(profileentry.JobExecutionsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(profileentry.JobExecutionsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(profileentry.JobExecutionsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(ulid.ID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*ulid.ID)
				inValue := *values[1].(*ulid.ID)
				if nids[inValue] == nil {
					nids[inValue] = map[*ProfileEntry]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*JobExecutionHistory](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "job_executions" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (peq *ProfileEntryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := peq.querySpec()
	if len(peq.modifiers) > 0 {
		_spec.Modifiers = peq.modifiers
	}
	_spec.Node.Columns = peq.ctx.Fields
	if len(peq.ctx.Fields) > 0 {
		_spec.Unique = peq.ctx.Unique != nil && *peq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, peq.driver, _spec)
}

func (peq *ProfileEntryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(profileentry.Table, profileentry.Columns, sqlgraph.NewFieldSpec(profileentry.FieldID, field.TypeString))
	_spec.From = peq.sql
	if unique := peq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if peq.path != nil {
		_spec.Unique = true
	}
	if fields := peq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profileentry.FieldID)
		for i := range fields {
			if fields[i] != profileentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := peq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := peq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := peq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := peq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (peq *ProfileEntryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(peq.driver.Dialect())
	t1 := builder.Table(profileentry.Table)
	columns := peq.ctx.Fields
	if len(columns) == 0 {
		columns = profileentry.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if peq.sql != nil {
		selector = peq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if peq.ctx.Unique != nil && *peq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range peq.predicates {
		p(selector)
	}
	for _, p := range peq.order {
		p(selector)
	}
	if offset := peq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := peq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedJobExecutions tells the query-builder to eager-load the nodes that are connected to the "job_executions"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (peq *ProfileEntryQuery) WithNamedJobExecutions(name string, opts ...func(*JobExecutionHistoryQuery)) *ProfileEntryQuery {
	query := (&JobExecutionHistoryClient{config: peq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if peq.withNamedJobExecutions == nil {
		peq.withNamedJobExecutions = make(map[string]*JobExecutionHistoryQuery)
	}
	peq.withNamedJobExecutions[name] = query
	return peq
}

// ProfileEntryGroupBy is the group-by builder for ProfileEntry entities.
type ProfileEntryGroupBy struct {
	selector
	build *ProfileEntryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pegb *ProfileEntryGroupBy) Aggregate(fns ...AggregateFunc) *ProfileEntryGroupBy {
	pegb.fns = append(pegb.fns, fns...)
	return pegb
}

// Scan applies the selector query and scans the result into the given value.
func (pegb *ProfileEntryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pegb.build.ctx, ent.OpQueryGroupBy)
	if err := pegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProfileEntryQuery, *ProfileEntryGroupBy](ctx, pegb.build, pegb, pegb.build.inters, v)
}

func (pegb *ProfileEntryGroupBy) sqlScan(ctx context.Context, root *ProfileEntryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pegb.fns))
	for _, fn := range pegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pegb.flds)+len(pegb.fns))
		for _, f := range *pegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProfileEntrySelect is the builder for selecting fields of ProfileEntry entities.
type ProfileEntrySelect struct {
	*ProfileEntryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pes *ProfileEntrySelect) Aggregate(fns ...AggregateFunc) *ProfileEntrySelect {
	pes.fns = append(pes.fns, fns...)
	return pes
}

// Scan applies the selector query and scans the result into the given value.
func (pes *ProfileEntrySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pes.ctx, ent.OpQuerySelect)
	if err := pes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProfileEntryQuery, *ProfileEntrySelect](ctx, pes.ProfileEntryQuery, pes, pes.inters, v)
}

func (pes *ProfileEntrySelect) sqlScan(ctx context.Context, root *ProfileEntryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pes.fns))
	for _, fn := range pes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
