// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"sheng-go-backend/ent/predicate"
	"sheng-go-backend/ent/profilepost"
	"sheng-go-backend/ent/profilepostitem"
	"sheng-go-backend/ent/schema/ulid"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfilePostItemQuery is the builder for querying ProfilePostItem entities.
type ProfilePostItemQuery struct {
	config
	ctx             *QueryContext
	order           []profilepostitem.OrderOption
	inters          []Interceptor
	predicates      []predicate.ProfilePostItem
	withProfilePost *ProfilePostQuery
	withFKs         bool
	modifiers       []func(*sql.Selector)
	loadTotal       []func(context.Context, []*ProfilePostItem) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProfilePostItemQuery builder.
func (ppiq *ProfilePostItemQuery) Where(ps ...predicate.ProfilePostItem) *ProfilePostItemQuery {
	ppiq.predicates = append(ppiq.predicates, ps...)
	return ppiq
}

// Limit the number of records to be returned by this query.
func (ppiq *ProfilePostItemQuery) Limit(limit int) *ProfilePostItemQuery {
	ppiq.ctx.Limit = &limit
	return ppiq
}

// Offset to start from.
func (ppiq *ProfilePostItemQuery) Offset(offset int) *ProfilePostItemQuery {
	ppiq.ctx.Offset = &offset
	return ppiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ppiq *ProfilePostItemQuery) Unique(unique bool) *ProfilePostItemQuery {
	ppiq.ctx.Unique = &unique
	return ppiq
}

// Order specifies how the records should be ordered.
func (ppiq *ProfilePostItemQuery) Order(o ...profilepostitem.OrderOption) *ProfilePostItemQuery {
	ppiq.order = append(ppiq.order, o...)
	return ppiq
}

// QueryProfilePost chains the current query on the "profile_post" edge.
func (ppiq *ProfilePostItemQuery) QueryProfilePost() *ProfilePostQuery {
	query := (&ProfilePostClient{config: ppiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ppiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ppiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(profilepostitem.Table, profilepostitem.FieldID, selector),
			sqlgraph.To(profilepost.Table, profilepost.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, profilepostitem.ProfilePostTable, profilepostitem.ProfilePostColumn),
		)
		fromU = sqlgraph.SetNeighbors(ppiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProfilePostItem entity from the query.
// Returns a *NotFoundError when no ProfilePostItem was found.
func (ppiq *ProfilePostItemQuery) First(ctx context.Context) (*ProfilePostItem, error) {
	nodes, err := ppiq.Limit(1).All(setContextOp(ctx, ppiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{profilepostitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ppiq *ProfilePostItemQuery) FirstX(ctx context.Context) *ProfilePostItem {
	node, err := ppiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProfilePostItem ID from the query.
// Returns a *NotFoundError when no ProfilePostItem ID was found.
func (ppiq *ProfilePostItemQuery) FirstID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = ppiq.Limit(1).IDs(setContextOp(ctx, ppiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{profilepostitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ppiq *ProfilePostItemQuery) FirstIDX(ctx context.Context) ulid.ID {
	id, err := ppiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProfilePostItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProfilePostItem entity is found.
// Returns a *NotFoundError when no ProfilePostItem entities are found.
func (ppiq *ProfilePostItemQuery) Only(ctx context.Context) (*ProfilePostItem, error) {
	nodes, err := ppiq.Limit(2).All(setContextOp(ctx, ppiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{profilepostitem.Label}
	default:
		return nil, &NotSingularError{profilepostitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ppiq *ProfilePostItemQuery) OnlyX(ctx context.Context) *ProfilePostItem {
	node, err := ppiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProfilePostItem ID in the query.
// Returns a *NotSingularError when more than one ProfilePostItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (ppiq *ProfilePostItemQuery) OnlyID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = ppiq.Limit(2).IDs(setContextOp(ctx, ppiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{profilepostitem.Label}
	default:
		err = &NotSingularError{profilepostitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ppiq *ProfilePostItemQuery) OnlyIDX(ctx context.Context) ulid.ID {
	id, err := ppiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProfilePostItems.
func (ppiq *ProfilePostItemQuery) All(ctx context.Context) ([]*ProfilePostItem, error) {
	ctx = setContextOp(ctx, ppiq.ctx, ent.OpQueryAll)
	if err := ppiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProfilePostItem, *ProfilePostItemQuery]()
	return withInterceptors[[]*ProfilePostItem](ctx, ppiq, qr, ppiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ppiq *ProfilePostItemQuery) AllX(ctx context.Context) []*ProfilePostItem {
	nodes, err := ppiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProfilePostItem IDs.
func (ppiq *ProfilePostItemQuery) IDs(ctx context.Context) (ids []ulid.ID, err error) {
	if ppiq.ctx.Unique == nil && ppiq.path != nil {
		ppiq.Unique(true)
	}
	ctx = setContextOp(ctx, ppiq.ctx, ent.OpQueryIDs)
	if err = ppiq.Select(profilepostitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ppiq *ProfilePostItemQuery) IDsX(ctx context.Context) []ulid.ID {
	ids, err := ppiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ppiq *ProfilePostItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ppiq.ctx, ent.OpQueryCount)
	if err := ppiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ppiq, querierCount[*ProfilePostItemQuery](), ppiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ppiq *ProfilePostItemQuery) CountX(ctx context.Context) int {
	count, err := ppiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ppiq *ProfilePostItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ppiq.ctx, ent.OpQueryExist)
	switch _, err := ppiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ppiq *ProfilePostItemQuery) ExistX(ctx context.Context) bool {
	exist, err := ppiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProfilePostItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ppiq *ProfilePostItemQuery) Clone() *ProfilePostItemQuery {
	if ppiq == nil {
		return nil
	}
	return &ProfilePostItemQuery{
		config:          ppiq.config,
		ctx:             ppiq.ctx.Clone(),
		order:           append([]profilepostitem.OrderOption{}, ppiq.order...),
		inters:          append([]Interceptor{}, ppiq.inters...),
		predicates:      append([]predicate.ProfilePostItem{}, ppiq.predicates...),
		withProfilePost: ppiq.withProfilePost.Clone(),
		// clone intermediate query.
		sql:  ppiq.sql.Clone(),
		path: ppiq.path,
	}
}

// WithProfilePost tells the query-builder to eager-load the nodes that are connected to
// the "profile_post" edge. The optional arguments are used to configure the query builder of the edge.
func (ppiq *ProfilePostItemQuery) WithProfilePost(opts ...func(*ProfilePostQuery)) *ProfilePostItemQuery {
	query := (&ProfilePostClient{config: ppiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ppiq.withProfilePost = query
	return ppiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProfileUsername string `json:"profile_username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProfilePostItem.Query().
//		GroupBy(profilepostitem.FieldProfileUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ppiq *ProfilePostItemQuery) GroupBy(field string, fields ...string) *ProfilePostItemGroupBy {
	ppiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProfilePostItemGroupBy{build: ppiq}
	grbuild.flds = &ppiq.ctx.Fields
	grbuild.label = profilepostitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProfileUsername string `json:"profile_username,omitempty"`
//	}
//
//	client.ProfilePostItem.Query().
//		Select(profilepostitem.FieldProfileUsername).
//		Scan(ctx, &v)
func (ppiq *ProfilePostItemQuery) Select(fields ...string) *ProfilePostItemSelect {
	ppiq.ctx.Fields = append(ppiq.ctx.Fields, fields...)
	sbuild := &ProfilePostItemSelect{ProfilePostItemQuery: ppiq}
	sbuild.label = profilepostitem.Label
	sbuild.flds, sbuild.scan = &ppiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProfilePostItemSelect configured with the given aggregations.
func (ppiq *ProfilePostItemQuery) Aggregate(fns ...AggregateFunc) *ProfilePostItemSelect {
	return ppiq.Select().Aggregate(fns...)
}

func (ppiq *ProfilePostItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ppiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ppiq); err != nil {
				return err
			}
		}
	}
	for _, f := range ppiq.ctx.Fields {
		if !profilepostitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ppiq.path != nil {
		prev, err := ppiq.path(ctx)
		if err != nil {
			return err
		}
		ppiq.sql = prev
	}
	return nil
}

func (ppiq *ProfilePostItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProfilePostItem, error) {
	var (
		nodes       = []*ProfilePostItem{}
		withFKs     = ppiq.withFKs
		_spec       = ppiq.querySpec()
		loadedTypes = [1]bool{
			ppiq.withProfilePost != nil,
		}
	)
	if ppiq.withProfilePost != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, profilepostitem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProfilePostItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProfilePostItem{config: ppiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ppiq.modifiers) > 0 {
		_spec.Modifiers = ppiq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ppiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ppiq.withProfilePost; query != nil {
		if err := ppiq.loadProfilePost(ctx, query, nodes, nil,
			func(n *ProfilePostItem, e *ProfilePost) { n.Edges.ProfilePost = e }); err != nil {
			return nil, err
		}
	}
	for i := range ppiq.loadTotal {
		if err := ppiq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ppiq *ProfilePostItemQuery) loadProfilePost(ctx context.Context, query *ProfilePostQuery, nodes []*ProfilePostItem, init func(*ProfilePostItem), assign func(*ProfilePostItem, *ProfilePost)) error {
	ids := make([]ulid.ID, 0, len(nodes))
	nodeids := make(map[ulid.ID][]*ProfilePostItem)
	for i := range nodes {
		if nodes[i].profile_post_items == nil {
			continue
		}
		fk := *nodes[i].profile_post_items
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(profilepost.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "profile_post_items" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ppiq *ProfilePostItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ppiq.querySpec()
	if len(ppiq.modifiers) > 0 {
		_spec.Modifiers = ppiq.modifiers
	}
	_spec.Node.Columns = ppiq.ctx.Fields
	if len(ppiq.ctx.Fields) > 0 {
		_spec.Unique = ppiq.ctx.Unique != nil && *ppiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ppiq.driver, _spec)
}

func (ppiq *ProfilePostItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(profilepostitem.Table, profilepostitem.Columns, sqlgraph.NewFieldSpec(profilepostitem.FieldID, field.TypeString))
	_spec.From = ppiq.sql
	if unique := ppiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ppiq.path != nil {
		_spec.Unique = true
	}
	if fields := ppiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profilepostitem.FieldID)
		for i := range fields {
			if fields[i] != profilepostitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ppiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ppiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ppiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ppiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ppiq *ProfilePostItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ppiq.driver.Dialect())
	t1 := builder.Table(profilepostitem.Table)
	columns := ppiq.ctx.Fields
	if len(columns) == 0 {
		columns = profilepostitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ppiq.sql != nil {
		selector = ppiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ppiq.ctx.Unique != nil && *ppiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ppiq.predicates {
		p(selector)
	}
	for _, p := range ppiq.order {
		p(selector)
	}
	if offset := ppiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ppiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProfilePostItemGroupBy is the group-by builder for ProfilePostItem entities.
type ProfilePostItemGroupBy struct {
	selector
	build *ProfilePostItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ppigb *ProfilePostItemGroupBy) Aggregate(fns ...AggregateFunc) *ProfilePostItemGroupBy {
	ppigb.fns = append(ppigb.fns, fns...)
	return ppigb
}

// Scan applies the selector query and scans the result into the given value.
func (ppigb *ProfilePostItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ppigb.build.ctx, ent.OpQueryGroupBy)
	if err := ppigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProfilePostItemQuery, *ProfilePostItemGroupBy](ctx, ppigb.build, ppigb, ppigb.build.inters, v)
}

func (ppigb *ProfilePostItemGroupBy) sqlScan(ctx context.Context, root *ProfilePostItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ppigb.fns))
	for _, fn := range ppigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ppigb.flds)+len(ppigb.fns))
		for _, f := range *ppigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ppigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ppigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProfilePostItemSelect is the builder for selecting fields of ProfilePostItem entities.
type ProfilePostItemSelect struct {
	*ProfilePostItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ppis *ProfilePostItemSelect) Aggregate(fns ...AggregateFunc) *ProfilePostItemSelect {
	ppis.fns = append(ppis.fns, fns...)
	return ppis
}

// Scan applies the selector query and scans the result into the given value.
func (ppis *ProfilePostItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ppis.ctx, ent.OpQuerySelect)
	if err := ppis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProfilePostItemQuery, *ProfilePostItemSelect](ctx, ppis.ProfilePostItemQuery, ppis, ppis.inters, v)
}

func (ppis *ProfilePostItemSelect) sqlScan(ctx context.Context, root *ProfilePostItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ppis.fns))
	for _, fn := range ppis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ppis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ppis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
