// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sheng-go-backend/ent/predicate"
	"sheng-go-backend/ent/profile"
	"sheng-go-backend/ent/profileentry"
	"sheng-go-backend/ent/schema/ulid"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileEntryUpdate is the builder for updating ProfileEntry entities.
type ProfileEntryUpdate struct {
	config
	hooks    []Hook
	mutation *ProfileEntryMutation
}

// Where appends a list predicates to the ProfileEntryUpdate builder.
func (peu *ProfileEntryUpdate) Where(ps ...predicate.ProfileEntry) *ProfileEntryUpdate {
	peu.mutation.Where(ps...)
	return peu
}

// SetUpdatedAt sets the "updated_at" field.
func (peu *ProfileEntryUpdate) SetUpdatedAt(t time.Time) *ProfileEntryUpdate {
	peu.mutation.SetUpdatedAt(t)
	return peu
}

// SetLinkedinUrn sets the "linkedin_urn" field.
func (peu *ProfileEntryUpdate) SetLinkedinUrn(s string) *ProfileEntryUpdate {
	peu.mutation.SetLinkedinUrn(s)
	return peu
}

// SetNillableLinkedinUrn sets the "linkedin_urn" field if the given value is not nil.
func (peu *ProfileEntryUpdate) SetNillableLinkedinUrn(s *string) *ProfileEntryUpdate {
	if s != nil {
		peu.SetLinkedinUrn(*s)
	}
	return peu
}

// SetGender sets the "gender" field.
func (peu *ProfileEntryUpdate) SetGender(s string) *ProfileEntryUpdate {
	peu.mutation.SetGender(s)
	return peu
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (peu *ProfileEntryUpdate) SetNillableGender(s *string) *ProfileEntryUpdate {
	if s != nil {
		peu.SetGender(*s)
	}
	return peu
}

// ClearGender clears the value of the "gender" field.
func (peu *ProfileEntryUpdate) ClearGender() *ProfileEntryUpdate {
	peu.mutation.ClearGender()
	return peu
}

// SetStatus sets the "status" field.
func (peu *ProfileEntryUpdate) SetStatus(pr profileentry.Status) *ProfileEntryUpdate {
	peu.mutation.SetStatus(pr)
	return peu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (peu *ProfileEntryUpdate) SetNillableStatus(pr *profileentry.Status) *ProfileEntryUpdate {
	if pr != nil {
		peu.SetStatus(*pr)
	}
	return peu
}

// SetProfileData sets the "profile_data" field.
func (peu *ProfileEntryUpdate) SetProfileData(m map[string]interface{}) *ProfileEntryUpdate {
	peu.mutation.SetProfileData(m)
	return peu
}

// ClearProfileData clears the value of the "profile_data" field.
func (peu *ProfileEntryUpdate) ClearProfileData() *ProfileEntryUpdate {
	peu.mutation.ClearProfileData()
	return peu
}

// SetTemplateJSONS3Key sets the "template_json_s3_key" field.
func (peu *ProfileEntryUpdate) SetTemplateJSONS3Key(s string) *ProfileEntryUpdate {
	peu.mutation.SetTemplateJSONS3Key(s)
	return peu
}

// SetNillableTemplateJSONS3Key sets the "template_json_s3_key" field if the given value is not nil.
func (peu *ProfileEntryUpdate) SetNillableTemplateJSONS3Key(s *string) *ProfileEntryUpdate {
	if s != nil {
		peu.SetTemplateJSONS3Key(*s)
	}
	return peu
}

// ClearTemplateJSONS3Key clears the value of the "template_json_s3_key" field.
func (peu *ProfileEntryUpdate) ClearTemplateJSONS3Key() *ProfileEntryUpdate {
	peu.mutation.ClearTemplateJSONS3Key()
	return peu
}

// SetRawResponseS3Key sets the "raw_response_s3_key" field.
func (peu *ProfileEntryUpdate) SetRawResponseS3Key(s string) *ProfileEntryUpdate {
	peu.mutation.SetRawResponseS3Key(s)
	return peu
}

// SetNillableRawResponseS3Key sets the "raw_response_s3_key" field if the given value is not nil.
func (peu *ProfileEntryUpdate) SetNillableRawResponseS3Key(s *string) *ProfileEntryUpdate {
	if s != nil {
		peu.SetRawResponseS3Key(*s)
	}
	return peu
}

// ClearRawResponseS3Key clears the value of the "raw_response_s3_key" field.
func (peu *ProfileEntryUpdate) ClearRawResponseS3Key() *ProfileEntryUpdate {
	peu.mutation.ClearRawResponseS3Key()
	return peu
}

// SetFetchCount sets the "fetch_count" field.
func (peu *ProfileEntryUpdate) SetFetchCount(i int) *ProfileEntryUpdate {
	peu.mutation.ResetFetchCount()
	peu.mutation.SetFetchCount(i)
	return peu
}

// SetNillableFetchCount sets the "fetch_count" field if the given value is not nil.
func (peu *ProfileEntryUpdate) SetNillableFetchCount(i *int) *ProfileEntryUpdate {
	if i != nil {
		peu.SetFetchCount(*i)
	}
	return peu
}

// AddFetchCount adds i to the "fetch_count" field.
func (peu *ProfileEntryUpdate) AddFetchCount(i int) *ProfileEntryUpdate {
	peu.mutation.AddFetchCount(i)
	return peu
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (peu *ProfileEntryUpdate) SetLastFetchedAt(t time.Time) *ProfileEntryUpdate {
	peu.mutation.SetLastFetchedAt(t)
	return peu
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (peu *ProfileEntryUpdate) SetNillableLastFetchedAt(t *time.Time) *ProfileEntryUpdate {
	if t != nil {
		peu.SetLastFetchedAt(*t)
	}
	return peu
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (peu *ProfileEntryUpdate) ClearLastFetchedAt() *ProfileEntryUpdate {
	peu.mutation.ClearLastFetchedAt()
	return peu
}

// SetErrorMessage sets the "error_message" field.
func (peu *ProfileEntryUpdate) SetErrorMessage(s string) *ProfileEntryUpdate {
	peu.mutation.SetErrorMessage(s)
	return peu
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (peu *ProfileEntryUpdate) SetNillableErrorMessage(s *string) *ProfileEntryUpdate {
	if s != nil {
		peu.SetErrorMessage(*s)
	}
	return peu
}

// ClearErrorMessage clears the value of the "error_message" field.
func (peu *ProfileEntryUpdate) ClearErrorMessage() *ProfileEntryUpdate {
	peu.mutation.ClearErrorMessage()
	return peu
}

// SetProfileID sets the "profile" edge to the Profile entity by ID.
func (peu *ProfileEntryUpdate) SetProfileID(id ulid.ID) *ProfileEntryUpdate {
	peu.mutation.SetProfileID(id)
	return peu
}

// SetNillableProfileID sets the "profile" edge to the Profile entity by ID if the given value is not nil.
func (peu *ProfileEntryUpdate) SetNillableProfileID(id *ulid.ID) *ProfileEntryUpdate {
	if id != nil {
		peu = peu.SetProfileID(*id)
	}
	return peu
}

// SetProfile sets the "profile" edge to the Profile entity.
func (peu *ProfileEntryUpdate) SetProfile(p *Profile) *ProfileEntryUpdate {
	return peu.SetProfileID(p.ID)
}

// Mutation returns the ProfileEntryMutation object of the builder.
func (peu *ProfileEntryUpdate) Mutation() *ProfileEntryMutation {
	return peu.mutation
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (peu *ProfileEntryUpdate) ClearProfile() *ProfileEntryUpdate {
	peu.mutation.ClearProfile()
	return peu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (peu *ProfileEntryUpdate) Save(ctx context.Context) (int, error) {
	peu.defaults()
	return withHooks(ctx, peu.sqlSave, peu.mutation, peu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (peu *ProfileEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := peu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (peu *ProfileEntryUpdate) Exec(ctx context.Context) error {
	_, err := peu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (peu *ProfileEntryUpdate) ExecX(ctx context.Context) {
	if err := peu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (peu *ProfileEntryUpdate) defaults() {
	if _, ok := peu.mutation.UpdatedAt(); !ok {
		v := profileentry.UpdateDefaultUpdatedAt()
		peu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (peu *ProfileEntryUpdate) check() error {
	if v, ok := peu.mutation.LinkedinUrn(); ok {
		if err := profileentry.LinkedinUrnValidator(v); err != nil {
			return &ValidationError{Name: "linkedin_urn", err: fmt.Errorf(`ent: validator failed for field "ProfileEntry.linkedin_urn": %w`, err)}
		}
	}
	if v, ok := peu.mutation.Status(); ok {
		if err := profileentry.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProfileEntry.status": %w`, err)}
		}
	}
	if v, ok := peu.mutation.TemplateJSONS3Key(); ok {
		if err := profileentry.TemplateJSONS3KeyValidator(v); err != nil {
			return &ValidationError{Name: "template_json_s3_key", err: fmt.Errorf(`ent: validator failed for field "ProfileEntry.template_json_s3_key": %w`, err)}
		}
	}
	if v, ok := peu.mutation.RawResponseS3Key(); ok {
		if err := profileentry.RawResponseS3KeyValidator(v); err != nil {
			return &ValidationError{Name: "raw_response_s3_key", err: fmt.Errorf(`ent: validator failed for field "ProfileEntry.raw_response_s3_key": %w`, err)}
		}
	}
	if v, ok := peu.mutation.FetchCount(); ok {
		if err := profileentry.FetchCountValidator(v); err != nil {
			return &ValidationError{Name: "fetch_count", err: fmt.Errorf(`ent: validator failed for field "ProfileEntry.fetch_count": %w`, err)}
		}
	}
	return nil
}

func (peu *ProfileEntryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := peu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(profileentry.Table, profileentry.Columns, sqlgraph.NewFieldSpec(profileentry.FieldID, field.TypeString))
	if ps := peu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := peu.mutation.UpdatedAt(); ok {
		_spec.SetField(profileentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := peu.mutation.LinkedinUrn(); ok {
		_spec.SetField(profileentry.FieldLinkedinUrn, field.TypeString, value)
	}
	if value, ok := peu.mutation.Gender(); ok {
		_spec.SetField(profileentry.FieldGender, field.TypeString, value)
	}
	if peu.mutation.GenderCleared() {
		_spec.ClearField(profileentry.FieldGender, field.TypeString)
	}
	if value, ok := peu.mutation.Status(); ok {
		_spec.SetField(profileentry.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := peu.mutation.ProfileData(); ok {
		_spec.SetField(profileentry.FieldProfileData, field.TypeJSON, value)
	}
	if peu.mutation.ProfileDataCleared() {
		_spec.ClearField(profileentry.FieldProfileData, field.TypeJSON)
	}
	if value, ok := peu.mutation.TemplateJSONS3Key(); ok {
		_spec.SetField(profileentry.FieldTemplateJSONS3Key, field.TypeString, value)
	}
	if peu.mutation.TemplateJSONS3KeyCleared() {
		_spec.ClearField(profileentry.FieldTemplateJSONS3Key, field.TypeString)
	}
	if value, ok := peu.mutation.RawResponseS3Key(); ok {
		_spec.SetField(profileentry.FieldRawResponseS3Key, field.TypeString, value)
	}
	if peu.mutation.RawResponseS3KeyCleared() {
		_spec.ClearField(profileentry.FieldRawResponseS3Key, field.TypeString)
	}
	if value, ok := peu.mutation.FetchCount(); ok {
		_spec.SetField(profileentry.FieldFetchCount, field.TypeInt, value)
	}
	if value, ok := peu.mutation.AddedFetchCount(); ok {
		_spec.AddField(profileentry.FieldFetchCount, field.TypeInt, value)
	}
	if value, ok := peu.mutation.LastFetchedAt(); ok {
		_spec.SetField(profileentry.FieldLastFetchedAt, field.TypeTime, value)
	}
	if peu.mutation.LastFetchedAtCleared() {
		_spec.ClearField(profileentry.FieldLastFetchedAt, field.TypeTime)
	}
	if value, ok := peu.mutation.ErrorMessage(); ok {
		_spec.SetField(profileentry.FieldErrorMessage, field.TypeString, value)
	}
	if peu.mutation.ErrorMessageCleared() {
		_spec.ClearField(profileentry.FieldErrorMessage, field.TypeString)
	}
	if peu.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   profileentry.ProfileTable,
			Columns: []string{profileentry.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := peu.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   profileentry.ProfileTable,
			Columns: []string{profileentry.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, peu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profileentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	peu.mutation.done = true
	return n, nil
}

// ProfileEntryUpdateOne is the builder for updating a single ProfileEntry entity.
type ProfileEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfileEntryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (peuo *ProfileEntryUpdateOne) SetUpdatedAt(t time.Time) *ProfileEntryUpdateOne {
	peuo.mutation.SetUpdatedAt(t)
	return peuo
}

// SetLinkedinUrn sets the "linkedin_urn" field.
func (peuo *ProfileEntryUpdateOne) SetLinkedinUrn(s string) *ProfileEntryUpdateOne {
	peuo.mutation.SetLinkedinUrn(s)
	return peuo
}

// SetNillableLinkedinUrn sets the "linkedin_urn" field if the given value is not nil.
func (peuo *ProfileEntryUpdateOne) SetNillableLinkedinUrn(s *string) *ProfileEntryUpdateOne {
	if s != nil {
		peuo.SetLinkedinUrn(*s)
	}
	return peuo
}

// SetGender sets the "gender" field.
func (peuo *ProfileEntryUpdateOne) SetGender(s string) *ProfileEntryUpdateOne {
	peuo.mutation.SetGender(s)
	return peuo
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (peuo *ProfileEntryUpdateOne) SetNillableGender(s *string) *ProfileEntryUpdateOne {
	if s != nil {
		peuo.SetGender(*s)
	}
	return peuo
}

// ClearGender clears the value of the "gender" field.
func (peuo *ProfileEntryUpdateOne) ClearGender() *ProfileEntryUpdateOne {
	peuo.mutation.ClearGender()
	return peuo
}

// SetStatus sets the "status" field.
func (peuo *ProfileEntryUpdateOne) SetStatus(pr profileentry.Status) *ProfileEntryUpdateOne {
	peuo.mutation.SetStatus(pr)
	return peuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (peuo *ProfileEntryUpdateOne) SetNillableStatus(pr *profileentry.Status) *ProfileEntryUpdateOne {
	if pr != nil {
		peuo.SetStatus(*pr)
	}
	return peuo
}

// SetProfileData sets the "profile_data" field.
func (peuo *ProfileEntryUpdateOne) SetProfileData(m map[string]interface{}) *ProfileEntryUpdateOne {
	peuo.mutation.SetProfileData(m)
	return peuo
}

// ClearProfileData clears the value of the "profile_data" field.
func (peuo *ProfileEntryUpdateOne) ClearProfileData() *ProfileEntryUpdateOne {
	peuo.mutation.ClearProfileData()
	return peuo
}

// SetTemplateJSONS3Key sets the "template_json_s3_key" field.
func (peuo *ProfileEntryUpdateOne) SetTemplateJSONS3Key(s string) *ProfileEntryUpdateOne {
	peuo.mutation.SetTemplateJSONS3Key(s)
	return peuo
}

// SetNillableTemplateJSONS3Key sets the "template_json_s3_key" field if the given value is not nil.
func (peuo *ProfileEntryUpdateOne) SetNillableTemplateJSONS3Key(s *string) *ProfileEntryUpdateOne {
	if s != nil {
		peuo.SetTemplateJSONS3Key(*s)
	}
	return peuo
}

// ClearTemplateJSONS3Key clears the value of the "template_json_s3_key" field.
func (peuo *ProfileEntryUpdateOne) ClearTemplateJSONS3Key() *ProfileEntryUpdateOne {
	peuo.mutation.ClearTemplateJSONS3Key()
	return peuo
}

// SetRawResponseS3Key sets the "raw_response_s3_key" field.
func (peuo *ProfileEntryUpdateOne) SetRawResponseS3Key(s string) *ProfileEntryUpdateOne {
	peuo.mutation.SetRawResponseS3Key(s)
	return peuo
}

// SetNillableRawResponseS3Key sets the "raw_response_s3_key" field if the given value is not nil.
func (peuo *ProfileEntryUpdateOne) SetNillableRawResponseS3Key(s *string) *ProfileEntryUpdateOne {
	if s != nil {
		peuo.SetRawResponseS3Key(*s)
	}
	return peuo
}

// ClearRawResponseS3Key clears the value of the "raw_response_s3_key" field.
func (peuo *ProfileEntryUpdateOne) ClearRawResponseS3Key() *ProfileEntryUpdateOne {
	peuo.mutation.ClearRawResponseS3Key()
	return peuo
}

// SetFetchCount sets the "fetch_count" field.
func (peuo *ProfileEntryUpdateOne) SetFetchCount(i int) *ProfileEntryUpdateOne {
	peuo.mutation.ResetFetchCount()
	peuo.mutation.SetFetchCount(i)
	return peuo
}

// SetNillableFetchCount sets the "fetch_count" field if the given value is not nil.
func (peuo *ProfileEntryUpdateOne) SetNillableFetchCount(i *int) *ProfileEntryUpdateOne {
	if i != nil {
		peuo.SetFetchCount(*i)
	}
	return peuo
}

// AddFetchCount adds i to the "fetch_count" field.
func (peuo *ProfileEntryUpdateOne) AddFetchCount(i int) *ProfileEntryUpdateOne {
	peuo.mutation.AddFetchCount(i)
	return peuo
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (peuo *ProfileEntryUpdateOne) SetLastFetchedAt(t time.Time) *ProfileEntryUpdateOne {
	peuo.mutation.SetLastFetchedAt(t)
	return peuo
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (peuo *ProfileEntryUpdateOne) SetNillableLastFetchedAt(t *time.Time) *ProfileEntryUpdateOne {
	if t != nil {
		peuo.SetLastFetchedAt(*t)
	}
	return peuo
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (peuo *ProfileEntryUpdateOne) ClearLastFetchedAt() *ProfileEntryUpdateOne {
	peuo.mutation.ClearLastFetchedAt()
	return peuo
}

// SetErrorMessage sets the "error_message" field.
func (peuo *ProfileEntryUpdateOne) SetErrorMessage(s string) *ProfileEntryUpdateOne {
	peuo.mutation.SetErrorMessage(s)
	return peuo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (peuo *ProfileEntryUpdateOne) SetNillableErrorMessage(s *string) *ProfileEntryUpdateOne {
	if s != nil {
		peuo.SetErrorMessage(*s)
	}
	return peuo
}

// ClearErrorMessage clears the value of the "error_message" field.
func (peuo *ProfileEntryUpdateOne) ClearErrorMessage() *ProfileEntryUpdateOne {
	peuo.mutation.ClearErrorMessage()
	return peuo
}

// SetProfileID sets the "profile" edge to the Profile entity by ID.
func (peuo *ProfileEntryUpdateOne) SetProfileID(id ulid.ID) *ProfileEntryUpdateOne {
	peuo.mutation.SetProfileID(id)
	return peuo
}

// SetNillableProfileID sets the "profile" edge to the Profile entity by ID if the given value is not nil.
func (peuo *ProfileEntryUpdateOne) SetNillableProfileID(id *ulid.ID) *ProfileEntryUpdateOne {
	if id != nil {
		peuo = peuo.SetProfileID(*id)
	}
	return peuo
}

// SetProfile sets the "profile" edge to the Profile entity.
func (peuo *ProfileEntryUpdateOne) SetProfile(p *Profile) *ProfileEntryUpdateOne {
	return peuo.SetProfileID(p.ID)
}

// Mutation returns the ProfileEntryMutation object of the builder.
func (peuo *ProfileEntryUpdateOne) Mutation() *ProfileEntryMutation {
	return peuo.mutation
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (peuo *ProfileEntryUpdateOne) ClearProfile() *ProfileEntryUpdateOne {
	peuo.mutation.ClearProfile()
	return peuo
}

// Where appends a list predicates to the ProfileEntryUpdate builder.
func (peuo *ProfileEntryUpdateOne) Where(ps ...predicate.ProfileEntry) *ProfileEntryUpdateOne {
	peuo.mutation.Where(ps...)
	return peuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (peuo *ProfileEntryUpdateOne) Select(field string, fields ...string) *ProfileEntryUpdateOne {
	peuo.fields = append([]string{field}, fields...)
	return peuo
}

// Save executes the query and returns the updated ProfileEntry entity.
func (peuo *ProfileEntryUpdateOne) Save(ctx context.Context) (*ProfileEntry, error) {
	peuo.defaults()
	return withHooks(ctx, peuo.sqlSave, peuo.mutation, peuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (peuo *ProfileEntryUpdateOne) SaveX(ctx context.Context) *ProfileEntry {
	node, err := peuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (peuo *ProfileEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := peuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (peuo *ProfileEntryUpdateOne) ExecX(ctx context.Context) {
	if err := peuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (peuo *ProfileEntryUpdateOne) defaults() {
	if _, ok := peuo.mutation.UpdatedAt(); !ok {
		v := profileentry.UpdateDefaultUpdatedAt()
		peuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (peuo *ProfileEntryUpdateOne) check() error {
	if v, ok := peuo.mutation.LinkedinUrn(); ok {
		if err := profileentry.LinkedinUrnValidator(v); err != nil {
			return &ValidationError{Name: "linkedin_urn", err: fmt.Errorf(`ent: validator failed for field "ProfileEntry.linkedin_urn": %w`, err)}
		}
	}
	if v, ok := peuo.mutation.Status(); ok {
		if err := profileentry.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProfileEntry.status": %w`, err)}
		}
	}
	if v, ok := peuo.mutation.TemplateJSONS3Key(); ok {
		if err := profileentry.TemplateJSONS3KeyValidator(v); err != nil {
			return &ValidationError{Name: "template_json_s3_key", err: fmt.Errorf(`ent: validator failed for field "ProfileEntry.template_json_s3_key": %w`, err)}
		}
	}
	if v, ok := peuo.mutation.RawResponseS3Key(); ok {
		if err := profileentry.RawResponseS3KeyValidator(v); err != nil {
			return &ValidationError{Name: "raw_response_s3_key", err: fmt.Errorf(`ent: validator failed for field "ProfileEntry.raw_response_s3_key": %w`, err)}
		}
	}
	if v, ok := peuo.mutation.FetchCount(); ok {
		if err := profileentry.FetchCountValidator(v); err != nil {
			return &ValidationError{Name: "fetch_count", err: fmt.Errorf(`ent: validator failed for field "ProfileEntry.fetch_count": %w`, err)}
		}
	}
	return nil
}

func (peuo *ProfileEntryUpdateOne) sqlSave(ctx context.Context) (_node *ProfileEntry, err error) {
	if err := peuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profileentry.Table, profileentry.Columns, sqlgraph.NewFieldSpec(profileentry.FieldID, field.TypeString))
	id, ok := peuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProfileEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := peuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profileentry.FieldID)
		for _, f := range fields {
			if !profileentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profileentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := peuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := peuo.mutation.UpdatedAt(); ok {
		_spec.SetField(profileentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := peuo.mutation.LinkedinUrn(); ok {
		_spec.SetField(profileentry.FieldLinkedinUrn, field.TypeString, value)
	}
	if value, ok := peuo.mutation.Gender(); ok {
		_spec.SetField(profileentry.FieldGender, field.TypeString, value)
	}
	if peuo.mutation.GenderCleared() {
		_spec.ClearField(profileentry.FieldGender, field.TypeString)
	}
	if value, ok := peuo.mutation.Status(); ok {
		_spec.SetField(profileentry.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := peuo.mutation.ProfileData(); ok {
		_spec.SetField(profileentry.FieldProfileData, field.TypeJSON, value)
	}
	if peuo.mutation.ProfileDataCleared() {
		_spec.ClearField(profileentry.FieldProfileData, field.TypeJSON)
	}
	if value, ok := peuo.mutation.TemplateJSONS3Key(); ok {
		_spec.SetField(profileentry.FieldTemplateJSONS3Key, field.TypeString, value)
	}
	if peuo.mutation.TemplateJSONS3KeyCleared() {
		_spec.ClearField(profileentry.FieldTemplateJSONS3Key, field.TypeString)
	}
	if value, ok := peuo.mutation.RawResponseS3Key(); ok {
		_spec.SetField(profileentry.FieldRawResponseS3Key, field.TypeString, value)
	}
	if peuo.mutation.RawResponseS3KeyCleared() {
		_spec.ClearField(profileentry.FieldRawResponseS3Key, field.TypeString)
	}
	if value, ok := peuo.mutation.FetchCount(); ok {
		_spec.SetField(profileentry.FieldFetchCount, field.TypeInt, value)
	}
	if value, ok := peuo.mutation.AddedFetchCount(); ok {
		_spec.AddField(profileentry.FieldFetchCount, field.TypeInt, value)
	}
	if value, ok := peuo.mutation.LastFetchedAt(); ok {
		_spec.SetField(profileentry.FieldLastFetchedAt, field.TypeTime, value)
	}
	if peuo.mutation.LastFetchedAtCleared() {
		_spec.ClearField(profileentry.FieldLastFetchedAt, field.TypeTime)
	}
	if value, ok := peuo.mutation.ErrorMessage(); ok {
		_spec.SetField(profileentry.FieldErrorMessage, field.TypeString, value)
	}
	if peuo.mutation.ErrorMessageCleared() {
		_spec.ClearField(profileentry.FieldErrorMessage, field.TypeString)
	}
	if peuo.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   profileentry.ProfileTable,
			Columns: []string{profileentry.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := peuo.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   profileentry.ProfileTable,
			Columns: []string{profileentry.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProfileEntry{config: peuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, peuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profileentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	peuo.mutation.done = true
	return _node, nil
}
