// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"sheng-go-backend/ent/predicate"
	"sheng-go-backend/ent/profilepost"
	"sheng-go-backend/ent/profilepostitem"
	"sheng-go-backend/ent/schema/ulid"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfilePostQuery is the builder for querying ProfilePost entities.
type ProfilePostQuery struct {
	config
	ctx            *QueryContext
	order          []profilepost.OrderOption
	inters         []Interceptor
	predicates     []predicate.ProfilePost
	withItems      *ProfilePostItemQuery
	modifiers      []func(*sql.Selector)
	loadTotal      []func(context.Context, []*ProfilePost) error
	withNamedItems map[string]*ProfilePostItemQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProfilePostQuery builder.
func (ppq *ProfilePostQuery) Where(ps ...predicate.ProfilePost) *ProfilePostQuery {
	ppq.predicates = append(ppq.predicates, ps...)
	return ppq
}

// Limit the number of records to be returned by this query.
func (ppq *ProfilePostQuery) Limit(limit int) *ProfilePostQuery {
	ppq.ctx.Limit = &limit
	return ppq
}

// Offset to start from.
func (ppq *ProfilePostQuery) Offset(offset int) *ProfilePostQuery {
	ppq.ctx.Offset = &offset
	return ppq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ppq *ProfilePostQuery) Unique(unique bool) *ProfilePostQuery {
	ppq.ctx.Unique = &unique
	return ppq
}

// Order specifies how the records should be ordered.
func (ppq *ProfilePostQuery) Order(o ...profilepost.OrderOption) *ProfilePostQuery {
	ppq.order = append(ppq.order, o...)
	return ppq
}

// QueryItems chains the current query on the "items" edge.
func (ppq *ProfilePostQuery) QueryItems() *ProfilePostItemQuery {
	query := (&ProfilePostItemClient{config: ppq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ppq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ppq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(profilepost.Table, profilepost.FieldID, selector),
			sqlgraph.To(profilepostitem.Table, profilepostitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, profilepost.ItemsTable, profilepost.ItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(ppq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProfilePost entity from the query.
// Returns a *NotFoundError when no ProfilePost was found.
func (ppq *ProfilePostQuery) First(ctx context.Context) (*ProfilePost, error) {
	nodes, err := ppq.Limit(1).All(setContextOp(ctx, ppq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{profilepost.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ppq *ProfilePostQuery) FirstX(ctx context.Context) *ProfilePost {
	node, err := ppq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProfilePost ID from the query.
// Returns a *NotFoundError when no ProfilePost ID was found.
func (ppq *ProfilePostQuery) FirstID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = ppq.Limit(1).IDs(setContextOp(ctx, ppq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{profilepost.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ppq *ProfilePostQuery) FirstIDX(ctx context.Context) ulid.ID {
	id, err := ppq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProfilePost entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProfilePost entity is found.
// Returns a *NotFoundError when no ProfilePost entities are found.
func (ppq *ProfilePostQuery) Only(ctx context.Context) (*ProfilePost, error) {
	nodes, err := ppq.Limit(2).All(setContextOp(ctx, ppq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{profilepost.Label}
	default:
		return nil, &NotSingularError{profilepost.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ppq *ProfilePostQuery) OnlyX(ctx context.Context) *ProfilePost {
	node, err := ppq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProfilePost ID in the query.
// Returns a *NotSingularError when more than one ProfilePost ID is found.
// Returns a *NotFoundError when no entities are found.
func (ppq *ProfilePostQuery) OnlyID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = ppq.Limit(2).IDs(setContextOp(ctx, ppq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{profilepost.Label}
	default:
		err = &NotSingularError{profilepost.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ppq *ProfilePostQuery) OnlyIDX(ctx context.Context) ulid.ID {
	id, err := ppq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProfilePosts.
func (ppq *ProfilePostQuery) All(ctx context.Context) ([]*ProfilePost, error) {
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryAll)
	if err := ppq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProfilePost, *ProfilePostQuery]()
	return withInterceptors[[]*ProfilePost](ctx, ppq, qr, ppq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ppq *ProfilePostQuery) AllX(ctx context.Context) []*ProfilePost {
	nodes, err := ppq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProfilePost IDs.
func (ppq *ProfilePostQuery) IDs(ctx context.Context) (ids []ulid.ID, err error) {
	if ppq.ctx.Unique == nil && ppq.path != nil {
		ppq.Unique(true)
	}
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryIDs)
	if err = ppq.Select(profilepost.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ppq *ProfilePostQuery) IDsX(ctx context.Context) []ulid.ID {
	ids, err := ppq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ppq *ProfilePostQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryCount)
	if err := ppq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ppq, querierCount[*ProfilePostQuery](), ppq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ppq *ProfilePostQuery) CountX(ctx context.Context) int {
	count, err := ppq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ppq *ProfilePostQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryExist)
	switch _, err := ppq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ppq *ProfilePostQuery) ExistX(ctx context.Context) bool {
	exist, err := ppq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProfilePostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ppq *ProfilePostQuery) Clone() *ProfilePostQuery {
	if ppq == nil {
		return nil
	}
	return &ProfilePostQuery{
		config:     ppq.config,
		ctx:        ppq.ctx.Clone(),
		order:      append([]profilepost.OrderOption{}, ppq.order...),
		inters:     append([]Interceptor{}, ppq.inters...),
		predicates: append([]predicate.ProfilePost{}, ppq.predicates...),
		withItems:  ppq.withItems.Clone(),
		// clone intermediate query.
		sql:  ppq.sql.Clone(),
		path: ppq.path,
	}
}

// WithItems tells the query-builder to eager-load the nodes that are connected to
// the "items" edge. The optional arguments are used to configure the query builder of the edge.
func (ppq *ProfilePostQuery) WithItems(opts ...func(*ProfilePostItemQuery)) *ProfilePostQuery {
	query := (&ProfilePostItemClient{config: ppq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ppq.withItems = query
	return ppq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProfileUsername string `json:"profile_username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProfilePost.Query().
//		GroupBy(profilepost.FieldProfileUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ppq *ProfilePostQuery) GroupBy(field string, fields ...string) *ProfilePostGroupBy {
	ppq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProfilePostGroupBy{build: ppq}
	grbuild.flds = &ppq.ctx.Fields
	grbuild.label = profilepost.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProfileUsername string `json:"profile_username,omitempty"`
//	}
//
//	client.ProfilePost.Query().
//		Select(profilepost.FieldProfileUsername).
//		Scan(ctx, &v)
func (ppq *ProfilePostQuery) Select(fields ...string) *ProfilePostSelect {
	ppq.ctx.Fields = append(ppq.ctx.Fields, fields...)
	sbuild := &ProfilePostSelect{ProfilePostQuery: ppq}
	sbuild.label = profilepost.Label
	sbuild.flds, sbuild.scan = &ppq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProfilePostSelect configured with the given aggregations.
func (ppq *ProfilePostQuery) Aggregate(fns ...AggregateFunc) *ProfilePostSelect {
	return ppq.Select().Aggregate(fns...)
}

func (ppq *ProfilePostQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ppq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ppq); err != nil {
				return err
			}
		}
	}
	for _, f := range ppq.ctx.Fields {
		if !profilepost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ppq.path != nil {
		prev, err := ppq.path(ctx)
		if err != nil {
			return err
		}
		ppq.sql = prev
	}
	return nil
}

func (ppq *ProfilePostQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProfilePost, error) {
	var (
		nodes       = []*ProfilePost{}
		_spec       = ppq.querySpec()
		loadedTypes = [1]bool{
			ppq.withItems != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProfilePost).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProfilePost{config: ppq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ppq.modifiers) > 0 {
		_spec.Modifiers = ppq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ppq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ppq.withItems; query != nil {
		if err := ppq.loadItems(ctx, query, nodes,
			func(n *ProfilePost) { n.Edges.Items = []*ProfilePostItem{} },
			func(n *ProfilePost, e *ProfilePostItem) { n.Edges.Items = append(n.Edges.Items, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range ppq.withNamedItems {
		if err := ppq.loadItems(ctx, query, nodes,
			func(n *ProfilePost) { n.appendNamedItems(name) },
			func(n *ProfilePost, e *ProfilePostItem) { n.appendNamedItems(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range ppq.loadTotal {
		if err := ppq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ppq *ProfilePostQuery) loadItems(ctx context.Context, query *ProfilePostItemQuery, nodes []*ProfilePost, init func(*ProfilePost), assign func(*ProfilePost, *ProfilePostItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[ulid.ID]*ProfilePost)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ProfilePostItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(profilepost.ItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.profile_post_items
		if fk == nil {
			return fmt.Errorf(`foreign-key "profile_post_items" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "profile_post_items" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ppq *ProfilePostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ppq.querySpec()
	if len(ppq.modifiers) > 0 {
		_spec.Modifiers = ppq.modifiers
	}
	_spec.Node.Columns = ppq.ctx.Fields
	if len(ppq.ctx.Fields) > 0 {
		_spec.Unique = ppq.ctx.Unique != nil && *ppq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ppq.driver, _spec)
}

func (ppq *ProfilePostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(profilepost.Table, profilepost.Columns, sqlgraph.NewFieldSpec(profilepost.FieldID, field.TypeString))
	_spec.From = ppq.sql
	if unique := ppq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ppq.path != nil {
		_spec.Unique = true
	}
	if fields := ppq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profilepost.FieldID)
		for i := range fields {
			if fields[i] != profilepost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ppq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ppq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ppq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ppq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ppq *ProfilePostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ppq.driver.Dialect())
	t1 := builder.Table(profilepost.Table)
	columns := ppq.ctx.Fields
	if len(columns) == 0 {
		columns = profilepost.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ppq.sql != nil {
		selector = ppq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ppq.ctx.Unique != nil && *ppq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ppq.predicates {
		p(selector)
	}
	for _, p := range ppq.order {
		p(selector)
	}
	if offset := ppq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ppq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedItems tells the query-builder to eager-load the nodes that are connected to the "items"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (ppq *ProfilePostQuery) WithNamedItems(name string, opts ...func(*ProfilePostItemQuery)) *ProfilePostQuery {
	query := (&ProfilePostItemClient{config: ppq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if ppq.withNamedItems == nil {
		ppq.withNamedItems = make(map[string]*ProfilePostItemQuery)
	}
	ppq.withNamedItems[name] = query
	return ppq
}

// ProfilePostGroupBy is the group-by builder for ProfilePost entities.
type ProfilePostGroupBy struct {
	selector
	build *ProfilePostQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ppgb *ProfilePostGroupBy) Aggregate(fns ...AggregateFunc) *ProfilePostGroupBy {
	ppgb.fns = append(ppgb.fns, fns...)
	return ppgb
}

// Scan applies the selector query and scans the result into the given value.
func (ppgb *ProfilePostGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ppgb.build.ctx, ent.OpQueryGroupBy)
	if err := ppgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProfilePostQuery, *ProfilePostGroupBy](ctx, ppgb.build, ppgb, ppgb.build.inters, v)
}

func (ppgb *ProfilePostGroupBy) sqlScan(ctx context.Context, root *ProfilePostQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ppgb.fns))
	for _, fn := range ppgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ppgb.flds)+len(ppgb.fns))
		for _, f := range *ppgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ppgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ppgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProfilePostSelect is the builder for selecting fields of ProfilePost entities.
type ProfilePostSelect struct {
	*ProfilePostQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pps *ProfilePostSelect) Aggregate(fns ...AggregateFunc) *ProfilePostSelect {
	pps.fns = append(pps.fns, fns...)
	return pps
}

// Scan applies the selector query and scans the result into the given value.
func (pps *ProfilePostSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pps.ctx, ent.OpQuerySelect)
	if err := pps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProfilePostQuery, *ProfilePostSelect](ctx, pps.ProfilePostQuery, pps, pps.inters, v)
}

func (pps *ProfilePostSelect) sqlScan(ctx context.Context, root *ProfilePostQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pps.fns))
	for _, fn := range pps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
