// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sheng-go-backend/ent/predicate"
	"sheng-go-backend/ent/profilepostitem"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfilePostItemDelete is the builder for deleting a ProfilePostItem entity.
type ProfilePostItemDelete struct {
	config
	hooks    []Hook
	mutation *ProfilePostItemMutation
}

// Where appends a list predicates to the ProfilePostItemDelete builder.
func (ppid *ProfilePostItemDelete) Where(ps ...predicate.ProfilePostItem) *ProfilePostItemDelete {
	ppid.mutation.Where(ps...)
	return ppid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ppid *ProfilePostItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ppid.sqlExec, ppid.mutation, ppid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ppid *ProfilePostItemDelete) ExecX(ctx context.Context) int {
	n, err := ppid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ppid *ProfilePostItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(profilepostitem.Table, sqlgraph.NewFieldSpec(profilepostitem.FieldID, field.TypeString))
	if ps := ppid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ppid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ppid.mutation.done = true
	return affected, err
}

// ProfilePostItemDeleteOne is the builder for deleting a single ProfilePostItem entity.
type ProfilePostItemDeleteOne struct {
	ppid *ProfilePostItemDelete
}

// Where appends a list predicates to the ProfilePostItemDelete builder.
func (ppido *ProfilePostItemDeleteOne) Where(ps ...predicate.ProfilePostItem) *ProfilePostItemDeleteOne {
	ppido.ppid.mutation.Where(ps...)
	return ppido
}

// Exec executes the deletion query.
func (ppido *ProfilePostItemDeleteOne) Exec(ctx context.Context) error {
	n, err := ppido.ppid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{profilepostitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ppido *ProfilePostItemDeleteOne) ExecX(ctx context.Context) {
	if err := ppido.Exec(ctx); err != nil {
		panic(err)
	}
}
