// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sheng-go-backend/ent/predicate"
	"sheng-go-backend/ent/profile"
	"sheng-go-backend/ent/schema/ulid"
	"sheng-go-backend/ent/todo"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileUpdate is the builder for updating Profile entities.
type ProfileUpdate struct {
	config
	hooks    []Hook
	mutation *ProfileMutation
}

// Where appends a list predicates to the ProfileUpdate builder.
func (pu *ProfileUpdate) Where(ps ...predicate.Profile) *ProfileUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *ProfileUpdate) SetName(s string) *ProfileUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableName(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetTitle sets the "title" field.
func (pu *ProfileUpdate) SetTitle(s string) *ProfileUpdate {
	pu.mutation.SetTitle(s)
	return pu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableTitle(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetTitle(*s)
	}
	return pu
}

// SetUrn sets the "urn" field.
func (pu *ProfileUpdate) SetUrn(s string) *ProfileUpdate {
	pu.mutation.SetUrn(s)
	return pu
}

// SetNillableUrn sets the "urn" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableUrn(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetUrn(*s)
	}
	return pu
}

// SetSourceFile sets the "source_file" field.
func (pu *ProfileUpdate) SetSourceFile(s string) *ProfileUpdate {
	pu.mutation.SetSourceFile(s)
	return pu
}

// SetNillableSourceFile sets the "source_file" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableSourceFile(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetSourceFile(*s)
	}
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProfileUpdate) SetUpdatedAt(t time.Time) *ProfileUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// AddTodoIDs adds the "todos" edge to the Todo entity by IDs.
func (pu *ProfileUpdate) AddTodoIDs(ids ...ulid.ID) *ProfileUpdate {
	pu.mutation.AddTodoIDs(ids...)
	return pu
}

// AddTodos adds the "todos" edges to the Todo entity.
func (pu *ProfileUpdate) AddTodos(t ...*Todo) *ProfileUpdate {
	ids := make([]ulid.ID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return pu.AddTodoIDs(ids...)
}

// Mutation returns the ProfileMutation object of the builder.
func (pu *ProfileUpdate) Mutation() *ProfileMutation {
	return pu.mutation
}

// ClearTodos clears all "todos" edges to the Todo entity.
func (pu *ProfileUpdate) ClearTodos() *ProfileUpdate {
	pu.mutation.ClearTodos()
	return pu
}

// RemoveTodoIDs removes the "todos" edge to Todo entities by IDs.
func (pu *ProfileUpdate) RemoveTodoIDs(ids ...ulid.ID) *ProfileUpdate {
	pu.mutation.RemoveTodoIDs(ids...)
	return pu
}

// RemoveTodos removes "todos" edges to Todo entities.
func (pu *ProfileUpdate) RemoveTodos(t ...*Todo) *ProfileUpdate {
	ids := make([]ulid.ID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return pu.RemoveTodoIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProfileUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProfileUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProfileUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *ProfileUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := profile.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProfileUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := profile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Profile.name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Urn(); ok {
		if err := profile.UrnValidator(v); err != nil {
			return &ValidationError{Name: "urn", err: fmt.Errorf(`ent: validator failed for field "Profile.urn": %w`, err)}
		}
	}
	if v, ok := pu.mutation.SourceFile(); ok {
		if err := profile.SourceFileValidator(v); err != nil {
			return &ValidationError{Name: "source_file", err: fmt.Errorf(`ent: validator failed for field "Profile.source_file": %w`, err)}
		}
	}
	return nil
}

func (pu *ProfileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(profile.Table, profile.Columns, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(profile.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Title(); ok {
		_spec.SetField(profile.FieldTitle, field.TypeString, value)
	}
	if value, ok := pu.mutation.Urn(); ok {
		_spec.SetField(profile.FieldUrn, field.TypeString, value)
	}
	if value, ok := pu.mutation.SourceFile(); ok {
		_spec.SetField(profile.FieldSourceFile, field.TypeString, value)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(profile.FieldUpdatedAt, field.TypeTime, value)
	}
	if pu.mutation.TodosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TodosTable,
			Columns: []string{profile.TodosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(todo.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedTodosIDs(); len(nodes) > 0 && !pu.mutation.TodosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TodosTable,
			Columns: []string{profile.TodosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(todo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.TodosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TodosTable,
			Columns: []string{profile.TodosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(todo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProfileUpdateOne is the builder for updating a single Profile entity.
type ProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfileMutation
}

// SetName sets the "name" field.
func (puo *ProfileUpdateOne) SetName(s string) *ProfileUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableName(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetTitle sets the "title" field.
func (puo *ProfileUpdateOne) SetTitle(s string) *ProfileUpdateOne {
	puo.mutation.SetTitle(s)
	return puo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableTitle(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetTitle(*s)
	}
	return puo
}

// SetUrn sets the "urn" field.
func (puo *ProfileUpdateOne) SetUrn(s string) *ProfileUpdateOne {
	puo.mutation.SetUrn(s)
	return puo
}

// SetNillableUrn sets the "urn" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableUrn(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetUrn(*s)
	}
	return puo
}

// SetSourceFile sets the "source_file" field.
func (puo *ProfileUpdateOne) SetSourceFile(s string) *ProfileUpdateOne {
	puo.mutation.SetSourceFile(s)
	return puo
}

// SetNillableSourceFile sets the "source_file" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableSourceFile(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetSourceFile(*s)
	}
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProfileUpdateOne) SetUpdatedAt(t time.Time) *ProfileUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// AddTodoIDs adds the "todos" edge to the Todo entity by IDs.
func (puo *ProfileUpdateOne) AddTodoIDs(ids ...ulid.ID) *ProfileUpdateOne {
	puo.mutation.AddTodoIDs(ids...)
	return puo
}

// AddTodos adds the "todos" edges to the Todo entity.
func (puo *ProfileUpdateOne) AddTodos(t ...*Todo) *ProfileUpdateOne {
	ids := make([]ulid.ID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return puo.AddTodoIDs(ids...)
}

// Mutation returns the ProfileMutation object of the builder.
func (puo *ProfileUpdateOne) Mutation() *ProfileMutation {
	return puo.mutation
}

// ClearTodos clears all "todos" edges to the Todo entity.
func (puo *ProfileUpdateOne) ClearTodos() *ProfileUpdateOne {
	puo.mutation.ClearTodos()
	return puo
}

// RemoveTodoIDs removes the "todos" edge to Todo entities by IDs.
func (puo *ProfileUpdateOne) RemoveTodoIDs(ids ...ulid.ID) *ProfileUpdateOne {
	puo.mutation.RemoveTodoIDs(ids...)
	return puo
}

// RemoveTodos removes "todos" edges to Todo entities.
func (puo *ProfileUpdateOne) RemoveTodos(t ...*Todo) *ProfileUpdateOne {
	ids := make([]ulid.ID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return puo.RemoveTodoIDs(ids...)
}

// Where appends a list predicates to the ProfileUpdate builder.
func (puo *ProfileUpdateOne) Where(ps ...predicate.Profile) *ProfileUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProfileUpdateOne) Select(field string, fields ...string) *ProfileUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Profile entity.
func (puo *ProfileUpdateOne) Save(ctx context.Context) (*Profile, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProfileUpdateOne) SaveX(ctx context.Context) *Profile {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProfileUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *ProfileUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := profile.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProfileUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := profile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Profile.name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Urn(); ok {
		if err := profile.UrnValidator(v); err != nil {
			return &ValidationError{Name: "urn", err: fmt.Errorf(`ent: validator failed for field "Profile.urn": %w`, err)}
		}
	}
	if v, ok := puo.mutation.SourceFile(); ok {
		if err := profile.SourceFileValidator(v); err != nil {
			return &ValidationError{Name: "source_file", err: fmt.Errorf(`ent: validator failed for field "Profile.source_file": %w`, err)}
		}
	}
	return nil
}

func (puo *ProfileUpdateOne) sqlSave(ctx context.Context) (_node *Profile, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profile.Table, profile.Columns, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Profile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profile.FieldID)
		for _, f := range fields {
			if !profile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(profile.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Title(); ok {
		_spec.SetField(profile.FieldTitle, field.TypeString, value)
	}
	if value, ok := puo.mutation.Urn(); ok {
		_spec.SetField(profile.FieldUrn, field.TypeString, value)
	}
	if value, ok := puo.mutation.SourceFile(); ok {
		_spec.SetField(profile.FieldSourceFile, field.TypeString, value)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(profile.FieldUpdatedAt, field.TypeTime, value)
	}
	if puo.mutation.TodosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TodosTable,
			Columns: []string{profile.TodosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(todo.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedTodosIDs(); len(nodes) > 0 && !puo.mutation.TodosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TodosTable,
			Columns: []string{profile.TodosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(todo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.TodosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TodosTable,
			Columns: []string{profile.TodosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(todo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Profile{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
