// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIQuotaTracker is the predicate function for apiquotatracker builders.
type APIQuotaTracker func(*sql.Selector)

// CronJobConfig is the predicate function for cronjobconfig builders.
type CronJobConfig func(*sql.Selector)

// JobExecutionHistory is the predicate function for jobexecutionhistory builders.
type JobExecutionHistory func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// ProfileEntry is the predicate function for profileentry builders.
type ProfileEntry func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
